---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toolhive-operator-crds
  namespace: toolhive-system
spec:
  chartRef:
    kind: OCIRepository
    name: toolhive-operator-crds
    namespace: toolhive-system
  interval: 1h
