apiVersion: v1
kind: Secret
metadata:
  name: alert-secrets
  namespace: gatus
type: Opaque
stringData:
  DISCORD_WEBHOOK: ENC[AES256_GCM,data:qz+v16hyjMpvkHJ0jPsOC1VCsp767IsWZoog6RvDOyF/tbA1+7cA+quBzbCJXP8Zi4jDiXpphy7VHy/tpHwHVF7iiCNf7/KlZMNfxsdtQgqrG0pTJ7niVc+FXn0GCvyNx7bw1iSDkN+lKmQlUICDXK7GlacwiOx69g==,iv:3NdZ+35x+sPA6ZbUh5crR2Z7ybSAwi98UIWlcoB5wMY=,tag:Ufm7sBkbmIjyDA9P0qBeyQ==,type:str]
  HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:t2Ng6Kgkq6S7re6A+ZQ5vZQudFzDgpaWVEMwmy0YyRW0AIqyJqJf81uKleC+nv3ugJu3KYZTorCYNwhXCycS4uQqRxsiPZRMHLO1X7IYSbfIY2cwGAk7vFGppfm5PA7m3OKgXkuRLmgLqnwDU+qU2EvKhxXBVLkN0ooekL5ykc+EgOVyJcgUKo8UWSPDOgfNaI7sB2/2QZkyIZ2NSiUNBXAJyokm6UbKF2dQqzDWgJM0UPG3obga,iv:yMAKfMntEM1NM0g1yGaFm/Y12M4K8o4szyNRcSPRbrQ=,tag:X8ZrTtne8/lkY7LbFMGT1g==,type:str]
  PUSHOVER_TOKEN: ENC[AES256_GCM,data:BBJcz7wp/waC38mUhjhTSqh8S0gjBlTNv1z8hECG,iv:bWJw1P5/bjFI+7LMMkE9SEG7Bii+N9TfR3qQmTO9wwo=,tag:ZATejy1NWrojSB8O2QyvHQ==,type:str]
  PUSHOVER_USER_KEY: ENC[AES256_GCM,data:VhIWW3RU+HNPtyl/9NwJG5SycD50TOsYeXdaDCi9,iv:bZnM6inp03A2gpiSf4tMpQjQE6Okd5DTfBQDTp/yKxI=,tag:u9/o+z99L6Ta7WO/pVdqzA==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZ1ZkYS93MXhzejlaeXI3
        VEo2cU1mN25mUGthcUlBZHJrTG95aGZOU1c0CjZkd3NlQm5KRWNFUVdXeTJQMGR5
        dlJoMFNPNlAzMFM2WS9rQ0RMMUd3ZGMKLS0tIGFiY2VaMENCRjRScnRZeXZtWXlK
        NGFTQjRtMElJc3ozc3VTMFFuRGkrRG8KdwvxspzMpuFZEe0/RlPwlLLIEVdzs9D7
        KVkhbT7Xlctt6nzDu6A5o46lXow40ZfnsRQ7EW2YSSBu1R3mhH2wAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T02:43:04Z"
  mac: ENC[AES256_GCM,data:OcxHoG8CptRltWlx9fFs6X3bQi4Lcm0wPg2yyiH6vmmUmKffgQb49t/R0eOjBFxhMfoAJGOAWnyoJuwRXEVXHWimBRBOMqLqN+MtFHayf6P0Tnpl5kWOs5bBgeyDg4GfumQv78iV/WRAOvK5W2rQEm0zX1qZyBv/GvkqyY319U4=,iv:iYhyL21UL0i7eMphkvDkAmwbHWGlgiUOPiFZiecPwKM=,tag:mtNQs96PSI/vdOSMtDldhg==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
