apiVersion: v1
kind: Secret
metadata:
  name: mjolnir-backup-secret
  namespace: shares
type: Opaque
stringData:
  BMC_HOST: ENC[AES256_GCM,data:MISy36zOcK59BG4=,iv:28Rt8O0JalyHDTkYPD8DP7oGn+PvS7lnN5gxXHU3UaA=,tag:NMtkQMHwgblPVWbqd48Nsw==,type:str]
  BMC_USER: ENC[AES256_GCM,data:Ny6ZfdxMB1NnFGs=,iv:oOK2/oBEXxyvL/c8M13P5w9bg7+7wCy7mq8QGmjESLs=,tag:dVCh1d5cd9xlvgCIyyHWTw==,type:str]
  BMC_PASS: ENC[AES256_GCM,data:GwkyEgSWj/d9wCwlzJxLfWAM,iv:6Is2ZtFI7jpSvB0w8fSKXvKwtK+AgeuzuQFYnREutoY=,tag:d8AzkW8ofxJzpqKkH3MwGQ==,type:str]
  SRV_HOST: ENC[AES256_GCM,data:zfQbGY148su+1A==,iv:gAAVTyBkZ/0jQktx18MWxJVpCW86NnAC58q4is+ACe8=,tag:jb+XcD8fbbOextj3LiJwpw==,type:str]
  SRV_USER: ENC[AES256_GCM,data:3Ov6pTS09ER8K90=,iv:su0k7o35fE7do0b05gWJgyuH9GC1iIR4UYhrLAmSi3k=,tag:MFmQIz5bTsGd4qVpbV2kMA==,type:str]
  DEST_PATH: ENC[AES256_GCM,data:XDxssSYIONvPi94ttblE2rCkAQO+1C1Skg==,iv:uDS/1F91uMdrZn4F5q2FXyoyV2AnUKc0LDvO7uq/EJA=,tag:FIQuY84770vnmO6rHHn/zg==,type:str]
  ZFS_KEY_DATASET: ENC[AES256_GCM,data:solcnQ==,iv:fS1homflcUNKBLYlEDRiFEXFd0Hf8Ejz8U9PyZDkf1I=,tag:VCkOFqvDfgrE58Jg0NXoMQ==,type:str]
  ZFS_PASSPHRASE: ENC[AES256_GCM,data:XKxKd31XwTIPdzACqMbTDLw5Y1ObD5X1VnCitQUNC7Tm3rcN+4D83hok0c8lKQ2Q3cr9tqc52KVnVFVv42UoSezF9/a4bulkcqTLBMmzAvym4+ylWnnD9tgWth2DBV9+lhfbEKinF00B3hpjmn2zSxcpy0fdm2vBUq5kCsCJyXrD+b1E9WOrd0CsjxjKtZBZLc0xVFZylPf/pwswxQSIzv/gz5Ka1wvqxJUXupFB3JE3F53QkyWfz0vZBuvv/r3/pg1tJb/MhwF3PkI9a+AGZqxMxR7GexuQqJQP4nQuqiB2GmcCR/ds0wSUUDlt9QlyU69xxjz0qHgKgBvxxqg9pw==,iv:AnE0mp4+FJtK8bphoRY0Y3kzo4c4pKAenxSo3iC9sEM=,tag:eLcUhmUVD/lNs3KZrUP4+w==,type:str]
  TN_API_KEY: ENC[AES256_GCM,data:FpwKo1GEglTBLb9HTKb9BMsRzDFAEAt9qNyYwVsAptw6PLKsWoL72OsLM3wlvBqzKjigXhtcWJlmNc/BRemqFQkK,iv:LrrAA3SlO0S/2Cpflrk1UNrIITB8z40EITyqPFE1avg=,tag:IMcEQBFoPict0AERcOujnw==,type:str]
  DISCORD_WEBHOOK: ENC[AES256_GCM,data:sUKZJCXwHR1/6Wxw4EIIWn9X6plyiS/wiCMZpAQL7z7W8LHgqhYVR2neYqJaigv42ywtgzYDZJVhDQeAInqYVGS4QSLEag284AAIUsFo2ssBoSP2ZkNkWedXZTRNpVNREXhh2D28cATa9I2SnG+KNlkidj8HkuvY9A==,iv:IikecGZXAfcGHj/nM1WTBu2oZi3tQEsOSL5ivChYwRE=,tag:c16WVFR5UWGZo4OZkri6wA==,type:str]
  identity: ENC[AES256_GCM,data:pDGhhs+kvRJEYD8fsrgdWOUnuzhg8XLTgKw0FBtkmhV2pX/HeU7TG+1t2BrrCviYtyya+zZfsozokPa2KtMLsP+pxCJ+UlVm68L34wvZ+Tn/aT24dBMsaO60TwwprkspPbcJfXTTc0NKlECBz5pqWOKcLQKhHZev9rqxe8b3ZQp6savNMv8Zd0tTZdwFH1jsWumqw/cXuGnEemYNemt8XuCuSLsSmQS9g3A3RU3TZJBqZMrXtmRnh1r22EioPrGjgClGziLmEHmkYFe42MdJbS3cRVxZqVKMKf4RByWa0mDpHT2yhv5t6nJ8Ql/lhbWPAt/yylPTUVdNUPlkqw/2x1J4iy93o9u2nmtlUXJMDtpFl//0gpQJnrTIFx5SklMvK7T5wu6StXO6lKonEudvqHmW8rLsLwye5x4lNOgp9ZWNDk5n8SWslzZkzwlfrCkiThHW0RfKi0+iWO+IckwXfqPJnFjeZUDjmcY0cjHJOratU7q//PeLbjVNOmEewfQzJPbN4EDzuIS3bFsYNt6Y,iv:sh9tYwkQ82xjK8FZ8iW8YOMcqBOX4575E1XaDXGUDJU=,tag:u+N6qE99v08bzOkuSk5pFg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibVhkaHNpTk9RZFc0bHJq
        RjkvVFo0WjBoQngvMHdFL3ZGeWxySVJzOVRjCkE2dUZpdE1wR1RxbDlHUlVBdHhp
        MTAxd3hPUWJJcHc2UCtnMUpocXVrMjgKLS0tIEsvNGFuS0tCYmlKYmpaNmZpcG5Y
        aXoyRHRPT1ZXN1Z2SDNPeitSRVNGWDAKxh6p1AwQ+7m15JesnORqCrAlT5ZvYlQY
        qZOUZE1v+Dv1o/ywgOGiF82JJcTXJvdCDFzNOREfzY1HeM4rnKvRHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-28T02:00:09Z"
  mac: ENC[AES256_GCM,data:3FkLbTduSr36/TklCxxJRpok8I61ywOeB0BP1mn3lS6M/9rqsgstu0ENmyoYdVRl6lD67HAPVAUmjLPdqYf5d+G2o5SIsIbXPlh3IQ5aidf/NyroxyjMQuF949qFIQTTyLMdWEZmWbUK9AifajWRiUrJTYUcQwHtQ/x+UHcwC8I=,iv:EiebwupPVKWlFNTkbC9mGU6y1cUlSN3/MsXr+8wgiNo=,tag:jplSp6YfQbvF74fB9HyIsg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
