apiVersion: v1
kind: Secret
metadata:
  name: ultrafeeder-site
  namespace: adsb
type: Opaque
stringData:
  ALT: ENC[AES256_GCM,data:7PM1,iv:KfE7zWZVwa9M9s3c/9tP8s/ghB8kcp/TrVYLuZ5QTRs=,tag:lzg8B2kryz07DZOtrBQcpw==,type:str]
  HEYWHATSTHAT_PANORAMA_ID: ENC[AES256_GCM,data:Ggqo7GR6s8g=,iv:8NJz4M+D1CqnLA3zznhSVxTyuILox3hgTgUMcxKHTAU=,tag:Jg/VV0rlov6m/0RAhz+YYw==,type:str]
  LAT: ENC[AES256_GCM,data:ghDxajwsQmc=,iv:NoMs6S1TYc77pAwxwXTFfgj44dYECTRpnaGOOVpV/zs=,tag:bR13Z3N5Gow2+tWBNAiIQg==,type:str]
  LONG: ENC[AES256_GCM,data:zmdXrMLIp7tu,iv:QmAsWUjCOhnRgDYT4lnqPEZ8K3I0JcWPY1qBtwAC7cw=,tag:Ji2Gx1MvMYeN/0U+fWigkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc1NWQ3pJUitSOEdWUXJk
        aWUwQlY1MnE4dVNnWVFabVNZZXJOVUU0a1I0CjhYbUl6NXU4b0t4Rk1TZVpGTTc0
        U3p2R3VPc1hqakxqQ2JMcWxpTzk5MWcKLS0tIFdwVDArbGY0YnFxTmR6dVI2MDMw
        U3I5VlNPZWpyU3JsKzlOUHV2U0ZVS2cK6uFs5SxDFtaJL2ZtEGOoC6sYd3oHfkrY
        pKpo+KsDr3YmiTLF7n9rwAIbUmhhVzXTaWslKKBO1GyZf59k3Ma3+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-09-05T03:27:07Z"
  mac: ENC[AES256_GCM,data:3HykCmwy+jS7Jc0JMsbUE0zWt4Phq29nPlm05Oy7olpFde0ipvcb3FzWKmwIUEMHxZuWeEu9y4RfWvF7RKh2Bj9Sv+IAMobU8HKW05rcVa6+gvX14DktFrivuVQ6PBjhEfVPoLt6FmoH3VpsvEeLpElP08XJQc+K1YmDPhmU740=,iv:o/USoZwNP3XBC3fDP7oW81ib5dIeAyVNNesuoDSGUT0=,tag:5F0FI2oUQHxeB0WdQDWHzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: ultrafeeder-basic-auth
  namespace: adsb
type: Opaque
stringData:
  #ENC[AES256_GCM,data:jxxyOM243EIPdVgd+VU4q3DEKABS3vIcotIF4X+OzOcG,iv:6u0ynJg+NsnJzcxGbKtF5XrCWzyLAv8N/hRYABOS1+g=,tag:F9zpO3bohoGMqcDBo0FmiA==,type:comment]
  .htpasswd: ENC[AES256_GCM,data:2XFeMNUUUUFLnAis7D/pa3AQp7bsbpD916gxxhiU/0yo5gGbcko66ohy,iv:oTba2rDmipA1AASKUc2Cv/Z5/bRsffQiZHDHx9Y6vcU=,tag:w3kSRBNw8jW+P7KBruk7iw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEc1NWQ3pJUitSOEdWUXJk
        aWUwQlY1MnE4dVNnWVFabVNZZXJOVUU0a1I0CjhYbUl6NXU4b0t4Rk1TZVpGTTc0
        U3p2R3VPc1hqakxqQ2JMcWxpTzk5MWcKLS0tIFdwVDArbGY0YnFxTmR6dVI2MDMw
        U3I5VlNPZWpyU3JsKzlOUHV2U0ZVS2cK6uFs5SxDFtaJL2ZtEGOoC6sYd3oHfkrY
        pKpo+KsDr3YmiTLF7n9rwAIbUmhhVzXTaWslKKBO1GyZf59k3Ma3+A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-09-05T03:27:07Z"
  mac: ENC[AES256_GCM,data:3HykCmwy+jS7Jc0JMsbUE0zWt4Phq29nPlm05Oy7olpFde0ipvcb3FzWKmwIUEMHxZuWeEu9y4RfWvF7RKh2Bj9Sv+IAMobU8HKW05rcVa6+gvX14DktFrivuVQ6PBjhEfVPoLt6FmoH3VpsvEeLpElP08XJQc+K1YmDPhmU740=,iv:o/USoZwNP3XBC3fDP7oW81ib5dIeAyVNNesuoDSGUT0=,tag:5F0FI2oUQHxeB0WdQDWHzg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
