---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: kube-system
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: cilium-alert
  namespace: kube-system
spec:
  summary: "Cilium"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'cilium'
      namespace: kube-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: coredns-alert
  namespace: kube-system
spec:
  summary: "CoreDNS"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'coredns'
      namespace: kube-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: descheduler-alert
  namespace: kube-system
spec:
  summary: "Descheduler"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'descheduler'
      namespace: kube-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: device-plugin-alert
  namespace: kube-system
spec:
  summary: "Device Plugin"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'device-plugin'
      namespace: kube-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: metrics-server-alert
  namespace: kube-system
spec:
  summary: "Metrics Server"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'metrics-server'
      namespace: kube-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: reloader-alert
  namespace: kube-system
spec:
  summary: "Reloader"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'reloader'
      namespace: kube-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: spegel-alert
  namespace: kube-system
spec:
  summary: "Spegel"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: 'spegel'
      namespace: kube-system
