---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: grocy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grocy
    spec:
      securityContext:
        fsGroup: 911
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: grocy
          image: lscr.io/linuxserver/grocy:4.6.0@sha256:3734cf765d943120afc9b98ae36ac980bd498d37cd269cd5ad6be3c993ba22a2
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: /config
              name: grocy
          resources:
            requests:
              cpu: 2m
              memory: 90Mi
            limits:
              memory: 90Mi
          securityContext:
            capabilities:
              drop: ["ALL"]
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETUID
                - SETGID
                - NET_BIND_SERVICE
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: grocy
          persistentVolumeClaim:
            claimName: grocy
