---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: grocy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grocy
    spec:
      containers:
        - name: grocy
          image: lscr.io/linuxserver/grocy:4.5.0@sha256:6c3ef882f14c628d17e5630808dd850489a94feed8f127d2dfb0f71900a6e66e
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: /config
              name: grocy
          resources:
            requests:
              cpu: 2m
              memory: 90Mi
            limits:
              memory: 90Mi
      restartPolicy: Always
      volumes:
        - name: grocy
          persistentVolumeClaim:
            claimName: grocy
