---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocy
  namespace: grocy
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: grocy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grocy
    spec:
      containers:
        - name: grocy
          image: lscr.io/linuxserver/grocy:4.6.0@sha256:3734cf765d943120afc9b98ae36ac980bd498d37cd269cd5ad6be3c993ba22a2
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - mountPath: /config
              name: grocy
          resources:
            requests:
              cpu: 2m
              memory: 90Mi
            limits:
              memory: 90Mi
      restartPolicy: Always
      volumes:
        - name: grocy
          persistentVolumeClaim:
            claimName: grocy
