---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie
  namespace: mealie
spec:
  backup:
    target: primary
    volumeSnapshot:
      className: rook-ceph-cephfs-snapclass
      snapshotOwnerReference: cluster
  bootstrap:
    initdb:
      database: mealie
      owner: mealie
  enableSuperuserAccess: true
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: rook-cephfs
    size: 2Gi
