apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:7QkJsHSW4qnxlJp4rNfAzvaoOLMdD+fjH8YQWUV7LDGJm428/lE0rg==,iv:26h8TZ7P10mjwJA8GtcjxFUEwMgwHc45Vw3W4WFjy6Q=,tag:b9QNIdBzb17/P4XwWgPKdg==,type:str]
  RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:6eLM6GY=,iv:F3VF6JP+CFvx32zPqD3NkK2uQyjVWZ+ivuXN/Lbpm9U=,tag:RC23iZbNS6uUaIlgAPRjvQ==,type:str]
  RENOVATE_ENDPOINT: ENC[AES256_GCM,data:ER+UHq9owvj1zSsuwkI23QRPb69q8Q==,iv:ueYqxGogcfHCSa37yf+4JDz7QPlipzrAyBX62kzwWPo=,tag:mnYAC2OnGjsUaPLgS9nlWQ==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:oGRvKW5hcK5TWpZj3MGfixeGB8/A7zcYE3x2QZ+aKE+u0o7tdaU7QFHJntujnNQ77skpsM4qtcxOxVJKaiYM,iv:d3P2uJdCMAcl1O+1Rq6yH8Qwx/spi7vE8yZJTleBpuw=,tag:5xezUVG29aHtkLjgsuuTvw==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:MsvRIXrR,iv:u41Z7PmzobiyD5j+2D2z+EdX+uSFGNfaO3Wll2N1SLg=,tag:KVekc5PTn3PPLHW8H0oixw==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:fFWrslnpSHguUMfeAsRYnpi5c84mk5xzm9KdCUSZ1GIdMv1lx5CGeA==,iv:rCggmX2nCMf3vtHr+KrrtGWNOdweJP+hyfBEfYHuJVA=,tag:7GR1onK055dw6jGV8W+ATA==,type:str]
  RENOVATE_DOCKER_MAX_PAGES: ENC[AES256_GCM,data:EA==,iv:UKaoNUqk2BIBueHAX/yYyXahA5HxX8P1uMYTKJ8Ib3E=,tag:Y9yUkzLUa/hgFipTMeaN2w==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDU0FkZ09PUmVuakl3T25t
        eFdqTndwU1o1cVVzS2hIdTg2U3V6aFV5UTE4ClMzYUJ6QWtPcURQS1lkcm1ETHZ6
        aDFtVEVoL2RUOWVPV01yb2FzMzVtTkUKLS0tIGcrNUZCaXk5ZHMyc1c2am9heXpl
        SU9lNUpMdW1iOW9hWU1HOXJVb0dPdTgK9salM4iMMBPG+UwNs7OUPoHVQcEr4ewh
        hmEIabdQ45HCzPr6oFC7JuTpCooph30601AHY5CAYpPmgbFovZK9gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T03:11:27Z"
  mac: ENC[AES256_GCM,data:T6k1Os+T5RFDYOSYdOVhSr10oshlDHxLkOQjrOR3Y9mdIddsSfT3MoVtUAVy+0Nh/FzNVmgIu361vlEFeFEEAtQo1KL/3J8ztCDZbvulSLHJB4cvcTjL49iwJ6Vm9D7AvZlVOFqqqkE3FcCSk2a/NtWuDkKIQ4YHWYI+knQHONA=,iv:N1XD/I5y5+G1028wtwIUGaCyTZA7slhR9jRFqP6Pt2c=,tag:dw3X1dYLYaIP82WPRLZ4vA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
