apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:OLtvR9FPNrjpUB/yQlO0dzMcrL5Ab1dL0IpSQMM4nFFQmz3qoOrn2A==,iv:9SAmB5q/3qTLJhz53q+6q65cGnU7gyEURsA9ZYKDsn4=,tag:NqsL7aXlRFhzbkYMDxSTdA==,type:str]
  RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:ehDRlw==,iv:4xRdFfm4yTfs6MlNWGcwAHiLxkXRftR45PPWqIgk130=,tag:93/c9y7XiK6f8laSmBgadg==,type:str]
  RENOVATE_ENDPOINT: ENC[AES256_GCM,data:0+IRZf56Nri/ddj13mQ7zsVtyoTzcw==,iv:foo27e4HfKSyg+oYcYJrJKGDYuBqshmj9X/4l2pa6g0=,tag:JArVQxMfDzs44YnzGrGH4Q==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:JU64rDNgJvueyiGQIaq/DRPeuUL3f5XZqPn7TPOk8TbyJxnTXEUXe+vWQVcFFg5tqsWQhp4aNcxvkOILut9a,iv:Fdq+VjeYRWMbBY1//mpO6a0jrVvt4WMcee7cGIdl0gE=,tag:JwKOoVFrSQuF/lW6VLkvpg==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:t8cJWjv0,iv:7v148AtMgfpG63H9XT/dDAE3BU+CUSpnoKbGQRMkEE0=,tag:c9ExzxMF8ecZ7g6k9a6Ukg==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:pqBPYqxBm/e9DGXvVdILxm174DQTB0t7CGtk/fhFWOX1hb5E4FGGMQ==,iv:LuCzi2sN3lBDyyyK+K3wEkoehKGGBrlLNy0h+LX0/3Y=,tag:h68IDAMKKPu9Vzvu5Ti14A==,type:str]
  RENOVATE_DOCKER_MAX_PAGES: ENC[AES256_GCM,data:4w==,iv:vD3mlCVs8Wlbv23rcsXXzs3oWxNsQnBF9WqoTZKhNQE=,tag:cMQA8o7pJI9q5DC8ImTZUA==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGLzVlcUpydTRiKzdKbVFr
        Q2V5dXRiMzVKbzJoTmw1djlEeXc2Sk5XdGtnCkt2aGxXNnhnU1UwSHdzaWxWeHg2
        d1lMaGxZd2VWWmJNODN5VzhpcXR3d2MKLS0tIGRFZ3F5M1MwK1ArU05kYkUzQWhW
        dFVQWnJzSU9qTEtRZWM3NWhYQTdGQ1UK1KZpRo94a3RUU39LAclHepJTs4PLxrvN
        OinfYWEVQpcsy+fOWi829gdDPi3gsH6EmU8q/lKYDR+vGXxtwFg8tg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-26T03:32:33Z"
  mac: ENC[AES256_GCM,data:RoGTkgPuoYwlmOdOxvYgBzew2K2fdvDU+ZakDCeRtEEfSZwaZdK7uyQrluvBtEIvXkwG4eXEEFZsnbfcUcDvzqz2TGDLEqZFwZkxrOioj1d4gDwbkH6F7ycdGhcBhIJTUgvHuhS8dohoavXGTx2ptxxLWB2hMGC90/1Z2AXj16o=,iv:iTUS+iRmQ0oGPCDHlB40RrlcE2zAd6135rXUTEarZ3s=,tag:sASL5qeprfl47jHeUMOEnA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
