apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:Jrf7fYsrzA6R6WigBN4jk9bhjv4OAbfmMCbFtkHIYCkUL9pY4Q4erA==,iv:B42qyXENVy8bgj4lSOY6/Z9GrO9O3ldvDj4g7IItn58=,tag:EH/2rPyITX9P5tddXHrF6A==,type:str]
  RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:rysXqC0=,iv:rN9hoxO4UMq7GEYKaFzCMJHErDuDmix0w0vUCVSVHuo=,tag:k3IqvZQfJLXMXWkyauYL2g==,type:str]
  RENOVATE_ENDPOINT: ENC[AES256_GCM,data:/iT80AtG4Khva1ZpDWrsd+/uadSpFw==,iv:22aPPIbsUdSldRfCVEuCD2YqDnLlTLwxq5VeA+A5Row=,tag:krb+WPGwgv1bzaBZwobt1A==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:UwaEZuJk8nmnI/PsgVXvCVWCr335iz88Ichq3yxhJSnXWDZICqaWys+nmy1iEhhaffwrJlOUzZlvaHJU8OCc,iv:h4r+/AxtU+pBdXQa9rq4WF77UlEAoGaGO7oApfKcbzg=,tag:yUxobEsvgStoRDs4QC53sw==,type:str]
  RENOVATE_PLATFORM: ENC[AES256_GCM,data:DkxUrh1c,iv:gYylVOXb5KUVrJYUrqD5OFTvRmUf30sX7Sky/R3V4gQ=,tag:B7EDT20mflBRGKGtRrNxeA==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:RXt1YZH+FsyeHvfl7SaCTZun7nlGTbRF3ilmFwP4NJL3m+7qA4VYuw==,iv:yg/eW0/WIKIIT9RCl0qJeWAcMGtzJ2r0sCz9/dKnmNM=,tag:tFyySwZanhlK6Xl8l6stqg==,type:str]
  RENOVATE_DOCKER_MAX_PAGES: ENC[AES256_GCM,data:Dw==,iv:z5SzjD0D/wP2S9IJ9nYDdRXxVuODwqJ+vPRujaG1X5I=,tag:SEtA/MnsLTSEYK2W8WKLBA==,type:int]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeTg1R1ZZSFpmRGxlM1h1
        RmR3VzhLUzQydDdOVmRYZUY5MlE5NzkwRDF3Cm0wQUdLSXd0YnBxcEhIVmhNR2dZ
        bmlKTWZVaTFudHA0ZnU5NG1vNU1QZVEKLS0tIG9qS3hLYnlQM1JzNDdHbkI0cnZr
        SXdZUUJuMWpDU2JmRjIxa1NpS2toUGMKF2OPY2QABy1YX5gENmw0qBhhGvmDDq5q
        Ivhu3SKBoQIWeLFjgqckHZXwgoLWpK/daENegvJntAFJS4kOJrxgfQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-12T02:42:28Z"
  mac: ENC[AES256_GCM,data:Zq+VKpBr9oMV+Af6Q9/x+1uuKCSRY2o4zeaZeMPpbNh53ikEZxTypE7XJPxoZldj+/Daof6WX0tvv9+XNl7XLmdzxpeBbv72ASkID79wybvTcV0e5CYrfvUD91WwjpjK+xDBj74VItwvXHM+JbwlkIkQeN1n68aQfFTcou5pCh8=,iv:22vRJd+8qqtbQ4y3a16c2Cndg8l0MvMSqpECkXRdG9U=,tag:0NphVVU9uqsaP9wsXDxPZA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
