---
apiVersion: v1
kind: Namespace
metadata:
  name: shares
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: shares
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
