---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-audiobooks
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 60Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-books
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-dvr
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-downloads
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-movies
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 15Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-music
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 60Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-photos
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-preroll
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-processed
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-rips
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-tv
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 15Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-workouts
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  resources:
    requests:
      storage: 100Gi
