---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: media
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: media-handbrake-alert
  namespace: media
spec:
  summary: "HandBrake"
  providerRef:
    name: discord
  eventSeverity: info
  exclusionList:
    - "Dependencies do not meet ready condition"
  eventSources:
    - kind: Kustomization
      name: 'media-handbrake'
      namespace: media
    - kind: HelmRelease
      name: 'handbrake'
      namespace: media
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: media-plex-alert
  namespace: media
spec:
  summary: "Plex"
  providerRef:
    name: discord
  eventSeverity: info
  exclusionList:
    - "Dependencies do not meet ready condition"
  eventSources:
    - kind: Kustomization
      name: 'media-plex'
      namespace: media
    - kind: HelmRelease
      name: 'plex'
      namespace: media
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: media-storage-alert
  namespace: media
spec:
  summary: "Media Storage"
  providerRef:
    name: discord
  eventSeverity: info
  exclusionList:
    - "Dependencies do not meet ready condition"
  eventSources:
    - kind: Kustomization
      name: 'media-storage'
      namespace: media
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: media-tautulli-alert
  namespace: media
spec:
  summary: "Tautulli"
  providerRef:
    name: discord
  eventSeverity: info
  exclusionList:
    - "Dependencies do not meet ready condition"
  eventSources:
    - kind: Kustomization
      name: 'media-tautulli'
      namespace: media
    - kind: HelmRelease
      name: 'tautulli'
      namespace: media
