---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sparky
  namespace: sparkyfitness
spec:
  backup:
    target: primary
    volumeSnapshot:
      className: rook-ceph-cephfs-snapclass
      snapshotOwnerReference: cluster
  bootstrap:
    initdb:
      database: sparky
      owner: sparky
  enableSuperuserAccess: true
  instances: 3
  storage:
    storageClass: rook-cephfs
    size: 2Gi
