---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding
  namespace: linkding
spec:
  backup:
    target: primary
    volumeSnapshot:
      className: rook-ceph-cephfs-snapclass
      snapshotOwnerReference: cluster
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: rook-cephfs
    size: 3Gi
