---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding
  namespace: linkding
spec:
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: rook-cephbp
    size: 3Gi
