apiVersion: v1
stringData:
  github_token: ENC[AES256_GCM,data:bUczZS1HCs/83zN6d2OI1BpWAuJbUzK5ZvkqNYZ98621hb+LLaovug==,iv:ls1h1/UZMAQW7UdMpfEppw+vocRNx1TLAmeA0t5vmos=,tag:LvauC8VEbrsvLJLrlpXQ9A==,type:str]
kind: Secret
metadata:
  name: arc-token
  namespace: arc-runners
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUG93Sjk0ZFdZaUVlaU9X
        bE5pT1VmdHd5SE9HZWl0V0pLa3ExcUVvWlgwCkVoQlp1MlBnTW1BZGNGc2JYY0s0
        U1pLcUVkeEZWSFE1UkFObjJ1UHV4NUUKLS0tIGg3aGE3SEVKTDJoNXJBNnRNTnVw
        N2t5ekFJRGJIa3ptNm9IM3p3Y1Z1ZWcKsA6ha99Qk3iaFb/LAUkY65ObZ1CGHjal
        klJElJmgXQZBiY8M/V909G/0N6+SgNOQSnuRyyC+tMyUK488/hOjUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-08T03:50:06Z"
  mac: ENC[AES256_GCM,data:LU7qUrX9fCNTPZ7Jh0Xm03hQ16GDQNyAvvYEw9xkTS+SvWRKZ75MeWzrnV2mMlt0DZsoCtwtDVNZrpJWmSFHXsG3zpdJWU3uf4g5mRHiw9/RaJZBqKQivAO1leTGP/w+mIBsOzWXaOt64POAXR2G5D9cvetRAvP66+pt0OGSVCM=,iv:J4prZ5xSeFA40Q6bJ+SEJcXpseKKvJIpFFs+yD2Vouk=,tag:gJOmlrUrl1e7lx6qMk58MQ==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.1
