---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: node-feature-discovery
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: node-feature-discovery-kustomization-alert
  namespace: node-feature-discovery
spec:
  summary: "Node Feature Discovery"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: node-feature-discovery
