---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: openwebui-scheduled-backup
  namespace: openwebui
spec:
  immediate: true
  schedule: "0 0 7 * * *"
  backupOwnerReference: self
  cluster:
    name: openwebui
  method: volumeSnapshot
  target: primary
