apiVersion: v1
kind: Secret
metadata:
  name: backblaze-b2-volsync
  namespace: volsync
type: Opaque
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:XgAOK/amT8QSecx7ubRgHVBqKWXc+RCdAkpm/aHyQRXotkG6nURuv3LmU8sfKgA/3Jqx4VZf,iv:cdSW1Q+WHjDaUbwBE4P0SV/o9DdiItlOHB0+fXEVLnc=,tag:cPRERb49xq3R9n4Lw/Rtdw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:1MxFeuanaALofe9AIY4qGZ5vC3Pq9S9g6PSYDHMJSjX6dWxoKBYVvT9pn1uRD1qeWQj0UXfwu6ZE6voG+UGfDbQ2FhYn6CLCWzVVSHB3b5kOYC8E9cZNfMEJNEcnMlu4wgAFNP2Iw0mVNJZO0XVZ6vJBnqp5P2OL/az1CfwtT48=,iv:24MIEM6RFp6CveSP0ZLGwX9fp1yOA8Dn0e11lKnO2rc=,tag:+GcNtD1MkT68fcPmO9IgFw==,type:str]
  B2_KEY_ID: ENC[AES256_GCM,data:etyEcTxkwW0bNt7eHi24bP7fPeeuS2NLmA==,iv:jQTChhMGWjmvQt6d+9yvKjI6JoVN4bqoqujZlvdlhf4=,tag:wrH7GTDCI/PmrjTPWSPIfQ==,type:str]
  B2_APPLICATION_KEY: ENC[AES256_GCM,data:HBa7UkFroRR6ucd84jSbfAsSAkJrwY+gBwal8UWteg==,iv:oIt2ObYgEkMvqWWuhP9XRaK9P7lnQ5dtC97YEPAbEfY=,tag:QhVoOMoGgxviEay1q1vs/g==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bUtjSkJmL0lUdi9NK1Jx
        UlN2MkI1U25OSDRSNEtxTGU2VXNEMy9sY1FRCmdjUzJHSDkwNS9mVlZ3YVdRc3Qz
        MUFOb3FlWVZld0hiaEhRK29OSnFKMjgKLS0tIHdPTDR6MkFLYldqRk56RlZNS1VC
        QWN2bHlCUWxKSzVYKzlXYTlLUkFUWGMKdc4D6K6un5DCIMstPMYv8dZeVueRaVSj
        i5vQXyBGkFUBwImO+w5SmEvOPlZYpU3FX/2WRpHLsNhHSdXXmVHlSA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T02:26:25Z"
  mac: ENC[AES256_GCM,data:cn7hXvwOkrmEdbVnMOUjy3++PrF3Po1iIIMolQ8Mkn2V22YavT7cYaa/7g0JDM7mMJf6AHSN+a82hzq6oBdTl9SrelXPijMA257DsZHN/UnGzEUsY+5xzPDuR9/HF1Y18Cx4XE10gXuZdhgffn8BKG4JWrG6S6vOiXra9Ql+8Cs=,iv:CEcelJ1mWpkPjGQULPKidUAmiPJE7gCbWU2HyQhRgGQ=,tag:kqo/p9MrIxfB950QspTL4g==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
