---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: tailscale-operator-alert
  namespace: flux-system
spec:
  summary: "Tailscale Operator"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: tailscale
    - kind: HelmRepository
      name: '*'
      namespace: tailscale
    - kind: HelmChart
      name: '*'
      namespace: tailscale
    - kind: HelmRelease
      name: '*'
      namespace: tailscale
