---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: endurain
  namespace: endurain
spec:
  backup:
    target: primary
    volumeSnapshot:
      className: rook-ceph-cephfs-snapclass
      snapshotOwnerReference: cluster
  bootstrap:
    initdb:
      database: endurain
      owner: endurain
  enableSuperuserAccess: true
  instances: 3
  storage:
    storageClass: rook-cephfs
    size: 2Gi
