---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dndwiki
  namespace: dndwiki
spec:
  bootstrap:
    initdb:
      database: dndwiki
      owner: dndwiki
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: rook-cephbp
    size: 10Gi
