apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:fmPmA3PH1Zi7k95pE8L/X4cfjh5/vjjLQUi+S6bLcmw=,iv:x37U30WF/A86kOFxkzZaY9q4JVDDW70J4+gWbpX18VM=,tag:fwm6xAvp6PTeR/kFtOS/3A==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K2xWYk1rZVpKYzJmd1hh
        TllHQVk4WWdpcUxOWTlhMWgrQlptRkxmcEdNCllyRERjTjlmRVlZcXo4RUN6cXVO
        b0RGc0o1WVI4c0ZPM1VWdkpPTXRuWUEKLS0tIG14OCtWQW9HRmFmQTR0TDY0Ti9Z
        V0UybUJpU1hhc0RkWlJMOVVIRWgyT3cK+7wNMM6ZUYRWwJP3dCUTUcH4V6TID+o2
        /XB1NlQon/m3sC6hVY+/BKJaNtGjDg0RyehrXMXYBw5Sz6TmfdWmsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:50:10Z"
  mac: ENC[AES256_GCM,data:roUaKhIj/zupusgjgmRJMcGvaGTfc7K3qoLYcXnK0fvx/fOD1r1zcyMMgZktR/qDJ2DuYj7K670+9HnOexs/X0sLQBkbGci5+wTyAN6I98Og2FD1OrcQWB06RkPlays3zU7BmdMh0Av6UBDTFOTH97cAA976zIdAvMlbvyhZlFM=,iv:DtvANlxfexLvax3k8Hs7VNzP7bGJPIvEtgK5oKpPrCM=,tag:2NV4uyEWIrHFdJ+WFUrbMg==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:P9zQ7UEsp1E8dMI9dvmBsRqEEQ3fZ808eqfgoVkr5LwRUNa0bGQMAEUrulN+PJSmm2KtsmX4RWfarSAhYdyqrRgtzm9UUToOawczSfs0CZkioRvsWSGKiWkaOrEQzSGRnXvNjS89N+lNjleuFL0OZp9oxUIpSJrgCw==,iv:1bugSZE6FSc72ysEFUPTgjcmyO0c8lSdmS6+8MHX658=,tag:y/vSLy5zLRq9ROvv+MgGWA==,type:str]
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K2xWYk1rZVpKYzJmd1hh
        TllHQVk4WWdpcUxOWTlhMWgrQlptRkxmcEdNCllyRERjTjlmRVlZcXo4RUN6cXVO
        b0RGc0o1WVI4c0ZPM1VWdkpPTXRuWUEKLS0tIG14OCtWQW9HRmFmQTR0TDY0Ti9Z
        V0UybUJpU1hhc0RkWlJMOVVIRWgyT3cK+7wNMM6ZUYRWwJP3dCUTUcH4V6TID+o2
        /XB1NlQon/m3sC6hVY+/BKJaNtGjDg0RyehrXMXYBw5Sz6TmfdWmsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:50:10Z"
  mac: ENC[AES256_GCM,data:roUaKhIj/zupusgjgmRJMcGvaGTfc7K3qoLYcXnK0fvx/fOD1r1zcyMMgZktR/qDJ2DuYj7K670+9HnOexs/X0sLQBkbGci5+wTyAN6I98Og2FD1OrcQWB06RkPlays3zU7BmdMh0Av6UBDTFOTH97cAA976zIdAvMlbvyhZlFM=,iv:DtvANlxfexLvax3k8Hs7VNzP7bGJPIvEtgK5oKpPrCM=,tag:2NV4uyEWIrHFdJ+WFUrbMg==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:IiCzJgmN/V2k0NBCx1adskhvk/xhdjqbrGZXVoEma0caFS03mv+ddgnjV+/MGwj4KiYsycMSEiLuoog4jkTM/5WJ347xjtdMJv3pGoaAuTeTiv3HcbP3FpyMwF6AecR7T1joZBi04fiR+qtXegQcqUhZaB0qAoOmGHt86kz1GU1vHDRfJl5MLEals5qNFQ==,iv:okL5v08u3kMOesdwQlCPENN2Wth9Kss/hVVeEVLBKNk=,tag:KX8SDt7RnHoRUvBYyz7tQA==,type:str]
kind: Secret
metadata:
  name: pushover-webhook
  namespace: flux-system
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3K2xWYk1rZVpKYzJmd1hh
        TllHQVk4WWdpcUxOWTlhMWgrQlptRkxmcEdNCllyRERjTjlmRVlZcXo4RUN6cXVO
        b0RGc0o1WVI4c0ZPM1VWdkpPTXRuWUEKLS0tIG14OCtWQW9HRmFmQTR0TDY0Ti9Z
        V0UybUJpU1hhc0RkWlJMOVVIRWgyT3cK+7wNMM6ZUYRWwJP3dCUTUcH4V6TID+o2
        /XB1NlQon/m3sC6hVY+/BKJaNtGjDg0RyehrXMXYBw5Sz6TmfdWmsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:50:10Z"
  mac: ENC[AES256_GCM,data:roUaKhIj/zupusgjgmRJMcGvaGTfc7K3qoLYcXnK0fvx/fOD1r1zcyMMgZktR/qDJ2DuYj7K670+9HnOexs/X0sLQBkbGci5+wTyAN6I98Og2FD1OrcQWB06RkPlays3zU7BmdMh0Av6UBDTFOTH97cAA976zIdAvMlbvyhZlFM=,iv:DtvANlxfexLvax3k8Hs7VNzP7bGJPIvEtgK5oKpPrCM=,tag:2NV4uyEWIrHFdJ+WFUrbMg==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
