apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:D93XU3F0U1w76BVCRkAkq5XjpruOCqdMjsq0je5aYqw=,iv:4aGBZdaQXnQ1f1NT0GNR5wCwwtk8TEi7F/l10o+HoX0=,tag:QmJ0TIdwG5AiNgOR5LJw8g==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VjVZdFUxanhHNHZaLzZq
        T3BwR2YxM0JSR2lEU2hUVEd1QUpmZGF1UWhNClVDMERyV1V0Zm1Pc20xTDRsN2tw
        Q2REQ2piSGlhRkNibjhNTmNVWWFWbzAKLS0tIEJXK1hZWDlqeGVQemdWUDRTQURZ
        NjdKUzBDc0YrYjg4d1Y1UGw1bSsvRmsKt8gmq7gm2Hr7SzWD1k1kol7vcFmEBmgY
        xMy7WyBnL7AJcRYods1invdgQjYnrQxAo+9pk+r4zarLL5sp5U8PTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T03:22:13Z"
  mac: ENC[AES256_GCM,data:Kp/hYfSo/7wVGmIpBJARKh5nJ1hvXonn1+ttk3EfelHmMRKjglff3MIh6HZc/6F13QauYN86Bwi91sFLzzF3qdLqiYxO0V/lKzJ6mvtEVTMAzSG9QI9LpaEasjMgrKOwXkEBn1skP2AOr60V70tdP8/bzFtKd/5087chVejwjcA=,iv:BAXiIZXVnziHMbi3RW6cvrJgXpEP4hb2DrGVf6FQiYg=,tag:YPFLM1VU2RPNvd30b6/Y4Q==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:mh+VL6+5E2fYuSEgd5lZJSzgXcwEyQENUEhkm/OquYKDyksWoZrWYIQP212DV5NOT5UWJRos10ZHjohqwysdHuhThZ1I21YetcfmC9R6O0t1yMoTjKhiOhGxp45R9jNln9uR4Y84JxkrDc8AwmmECHOEJKbXvtC+1g==,iv:umMnm5owI2aSKsjnd2gXO5qgWUevUaf/P0E5urZsVMs=,tag:+9AJ76sxNqe9mGDJm6Qsgg==,type:str]
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VjVZdFUxanhHNHZaLzZq
        T3BwR2YxM0JSR2lEU2hUVEd1QUpmZGF1UWhNClVDMERyV1V0Zm1Pc20xTDRsN2tw
        Q2REQ2piSGlhRkNibjhNTmNVWWFWbzAKLS0tIEJXK1hZWDlqeGVQemdWUDRTQURZ
        NjdKUzBDc0YrYjg4d1Y1UGw1bSsvRmsKt8gmq7gm2Hr7SzWD1k1kol7vcFmEBmgY
        xMy7WyBnL7AJcRYods1invdgQjYnrQxAo+9pk+r4zarLL5sp5U8PTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T03:22:13Z"
  mac: ENC[AES256_GCM,data:Kp/hYfSo/7wVGmIpBJARKh5nJ1hvXonn1+ttk3EfelHmMRKjglff3MIh6HZc/6F13QauYN86Bwi91sFLzzF3qdLqiYxO0V/lKzJ6mvtEVTMAzSG9QI9LpaEasjMgrKOwXkEBn1skP2AOr60V70tdP8/bzFtKd/5087chVejwjcA=,iv:BAXiIZXVnziHMbi3RW6cvrJgXpEP4hb2DrGVf6FQiYg=,tag:YPFLM1VU2RPNvd30b6/Y4Q==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:rNC6jETUM2pq51bVIpMiixoN2OkwoT+28Ma9BwMJ1/8/C+O/v/0NuusMQmNgrCqOKfRe35fodBBQs8YoFDsFBohyUwkfb3HbnNfWHMuu0LLoArdMA25pCSgND/pldKmY+QBq1MUO3TsMALeO6WruvgtvcOfsw7vyqT931dSNHfTzcqk214d9t3TuVMB6SA==,iv:GU827bOqxg80gt5t4zYh3X90j6586KIxz/G/dTvvBas=,tag:2B9CwPNieMsohXPt9giLBQ==,type:str]
kind: Secret
metadata:
  name: pushover-webhook
  namespace: flux-system
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VjVZdFUxanhHNHZaLzZq
        T3BwR2YxM0JSR2lEU2hUVEd1QUpmZGF1UWhNClVDMERyV1V0Zm1Pc20xTDRsN2tw
        Q2REQ2piSGlhRkNibjhNTmNVWWFWbzAKLS0tIEJXK1hZWDlqeGVQemdWUDRTQURZ
        NjdKUzBDc0YrYjg4d1Y1UGw1bSsvRmsKt8gmq7gm2Hr7SzWD1k1kol7vcFmEBmgY
        xMy7WyBnL7AJcRYods1invdgQjYnrQxAo+9pk+r4zarLL5sp5U8PTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T03:22:13Z"
  mac: ENC[AES256_GCM,data:Kp/hYfSo/7wVGmIpBJARKh5nJ1hvXonn1+ttk3EfelHmMRKjglff3MIh6HZc/6F13QauYN86Bwi91sFLzzF3qdLqiYxO0V/lKzJ6mvtEVTMAzSG9QI9LpaEasjMgrKOwXkEBn1skP2AOr60V70tdP8/bzFtKd/5087chVejwjcA=,iv:BAXiIZXVnziHMbi3RW6cvrJgXpEP4hb2DrGVf6FQiYg=,tag:YPFLM1VU2RPNvd30b6/Y4Q==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Merge
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  name: sops-age
  namespace: flux-system
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VjVZdFUxanhHNHZaLzZq
        T3BwR2YxM0JSR2lEU2hUVEd1QUpmZGF1UWhNClVDMERyV1V0Zm1Pc20xTDRsN2tw
        Q2REQ2piSGlhRkNibjhNTmNVWWFWbzAKLS0tIEJXK1hZWDlqeGVQemdWUDRTQURZ
        NjdKUzBDc0YrYjg4d1Y1UGw1bSsvRmsKt8gmq7gm2Hr7SzWD1k1kol7vcFmEBmgY
        xMy7WyBnL7AJcRYods1invdgQjYnrQxAo+9pk+r4zarLL5sp5U8PTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-22T03:22:13Z"
  mac: ENC[AES256_GCM,data:Kp/hYfSo/7wVGmIpBJARKh5nJ1hvXonn1+ttk3EfelHmMRKjglff3MIh6HZc/6F13QauYN86Bwi91sFLzzF3qdLqiYxO0V/lKzJ6mvtEVTMAzSG9QI9LpaEasjMgrKOwXkEBn1skP2AOr60V70tdP8/bzFtKd/5087chVejwjcA=,iv:BAXiIZXVnziHMbi3RW6cvrJgXpEP4hb2DrGVf6FQiYg=,tag:YPFLM1VU2RPNvd30b6/Y4Q==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
