apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:VhKzSQqq9T+GqImDyx5IwQVKVJsnJ4Z+abuAfXnLiGE=,iv:vBIKgamPXcmObI0s9g2KfYV+kfcL+r9cNuooCh/ivmU=,tag:3nH96hGzCJxFUSbQFwkNDQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZDFUYXVaU0tJc0J4L0dV
        cVFPUDNEdEJBSUF1UGY4OWFrMElxNlNvcnlVCmg5M3U3RGk2SGdnS29Jdm14bm5s
        VEl5Tk9NZmE4eVhsSXp0a1ZCT0JockEKLS0tIEpjUGZCUHAvYTdLdjdVdjVDQVFM
        Yy9kWjEra3l6QWZmcjNHbFQ5by8xR0UKaBDenG3PZiY5t3JAnE5MjTJuCSNftj0D
        eEo0Jd3n0tEIGj+XsLQc5f8qK2LcQuXNIUKO065SQw4cp6sBx2mhnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-09T12:37:08Z"
  mac: ENC[AES256_GCM,data:Q5fNM0NwN8unI2wgljjZWoUXSJQGAbc5cBvoCf8SIr9nalv3B8zbvnwuNsJS03OjuRmjVokOIqrN20Xr14+QLfqpFEevrK0izZSKTf/VzBd9YEEQbhiXlE4A1/nh44bOlH4mtmS/HpGn+vJsCkk/z+THYRNuuXdVWZ+iSzFWjeg=,iv:ud3bGHjp7G3cFB3kO1dzBzGfWVCtFGgE83yleZznjHY=,tag:drtuPxF5NpjPm3p8mimTRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:4ZJhHIPWtQc5TS0nn/thPb+BtddxUuejnAUJjWm8NHavbOeP8D6MnCbLy16LSj4+vHGSrfIqnZtxejyH2H07HXwhyOuXLhiwociZeFp8zCNrw9SQoGoMCJj7GdFr7CRu2KIJrxUxBkHO1AOikGwdIfgkqlmhOfZz9w==,iv:ZB0Na+qqqjFgsOgOW4LpN8EeXiJjt6HaEt8EmLWINo4=,tag:X02b3ls/Mqj5leB29nLZQQ==,type:str]
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZDFUYXVaU0tJc0J4L0dV
        cVFPUDNEdEJBSUF1UGY4OWFrMElxNlNvcnlVCmg5M3U3RGk2SGdnS29Jdm14bm5s
        VEl5Tk9NZmE4eVhsSXp0a1ZCT0JockEKLS0tIEpjUGZCUHAvYTdLdjdVdjVDQVFM
        Yy9kWjEra3l6QWZmcjNHbFQ5by8xR0UKaBDenG3PZiY5t3JAnE5MjTJuCSNftj0D
        eEo0Jd3n0tEIGj+XsLQc5f8qK2LcQuXNIUKO065SQw4cp6sBx2mhnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-09T12:37:08Z"
  mac: ENC[AES256_GCM,data:Q5fNM0NwN8unI2wgljjZWoUXSJQGAbc5cBvoCf8SIr9nalv3B8zbvnwuNsJS03OjuRmjVokOIqrN20Xr14+QLfqpFEevrK0izZSKTf/VzBd9YEEQbhiXlE4A1/nh44bOlH4mtmS/HpGn+vJsCkk/z+THYRNuuXdVWZ+iSzFWjeg=,iv:ud3bGHjp7G3cFB3kO1dzBzGfWVCtFGgE83yleZznjHY=,tag:drtuPxF5NpjPm3p8mimTRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:cc0PHmDkYtrenL9QuT8e0+wUQz5i6zCdf0ILMqbN7hoLPQdf0p24L8ZGCqLXeN++QRghiGxhj7n0/d7XMZe700m9Ty3xzDRfQdhFa3gRYtcJlmdI/VofxhZloBaYiILSYldD9RldspdX8feIo5Veh3h4bkHyvB3PMbVL77c53a3inJxUqcd8nENLt6fbMw==,iv:gy2zqtK95rb4p3yBw3ftCvbwsuJnk5u8yMXpJiaHNT8=,tag:hPe4jsMdr7YFXxQGQNlocQ==,type:str]
kind: Secret
metadata:
  name: pushover-webhook
  namespace: flux-system
type: Opaque
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZDFUYXVaU0tJc0J4L0dV
        cVFPUDNEdEJBSUF1UGY4OWFrMElxNlNvcnlVCmg5M3U3RGk2SGdnS29Jdm14bm5s
        VEl5Tk9NZmE4eVhsSXp0a1ZCT0JockEKLS0tIEpjUGZCUHAvYTdLdjdVdjVDQVFM
        Yy9kWjEra3l6QWZmcjNHbFQ5by8xR0UKaBDenG3PZiY5t3JAnE5MjTJuCSNftj0D
        eEo0Jd3n0tEIGj+XsLQc5f8qK2LcQuXNIUKO065SQw4cp6sBx2mhnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-09T12:37:08Z"
  mac: ENC[AES256_GCM,data:Q5fNM0NwN8unI2wgljjZWoUXSJQGAbc5cBvoCf8SIr9nalv3B8zbvnwuNsJS03OjuRmjVokOIqrN20Xr14+QLfqpFEevrK0izZSKTf/VzBd9YEEQbhiXlE4A1/nh44bOlH4mtmS/HpGn+vJsCkk/z+THYRNuuXdVWZ+iSzFWjeg=,iv:ud3bGHjp7G3cFB3kO1dzBzGfWVCtFGgE83yleZznjHY=,tag:drtuPxF5NpjPm3p8mimTRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: Merge
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  name: sops-age
  namespace: flux-system
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZDFUYXVaU0tJc0J4L0dV
        cVFPUDNEdEJBSUF1UGY4OWFrMElxNlNvcnlVCmg5M3U3RGk2SGdnS29Jdm14bm5s
        VEl5Tk9NZmE4eVhsSXp0a1ZCT0JockEKLS0tIEpjUGZCUHAvYTdLdjdVdjVDQVFM
        Yy9kWjEra3l6QWZmcjNHbFQ5by8xR0UKaBDenG3PZiY5t3JAnE5MjTJuCSNftj0D
        eEo0Jd3n0tEIGj+XsLQc5f8qK2LcQuXNIUKO065SQw4cp6sBx2mhnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-09T12:37:08Z"
  mac: ENC[AES256_GCM,data:Q5fNM0NwN8unI2wgljjZWoUXSJQGAbc5cBvoCf8SIr9nalv3B8zbvnwuNsJS03OjuRmjVokOIqrN20Xr14+QLfqpFEevrK0izZSKTf/VzBd9YEEQbhiXlE4A1/nh44bOlH4mtmS/HpGn+vJsCkk/z+THYRNuuXdVWZ+iSzFWjeg=,iv:ud3bGHjp7G3cFB3kO1dzBzGfWVCtFGgE83yleZznjHY=,tag:drtuPxF5NpjPm3p8mimTRA==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
