---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-renovate-jobs
  namespace: renovate-operator
spec:
  podSelector:
    matchExpressions:
      - key: renovate-operator.mogenius.com/job-type
        operator: In
        values:
          - executor
          - discovery
  policyTypes:
    - Egress
  egress:
    - {}
