---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github-homelab
  namespace: renovate-operator
spec:
  discoveryFilters:
    - Peej11/**
  extraEnvFrom:
    - secretRef:
        name: renovate-secret
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_HOST_RULES
      value: >-
        [{"hostType":"docker","matchHost":"docker.io","username":"$(DOCKERHUB_USERNAME)","password":"$(DOCKERHUB_TOKEN)"}]
  image: ghcr.io/renovatebot/renovate:43.180.0@sha256:64acc02b94a8d51f71f31de8045e62c06fcbeac441f7ef22ac0d9c6e3d0712e5
  parallelism: 5
  provider:
    endpoint: "https://api.github.com/"
    name: "github"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: WEBHOOK_TOKEN
