---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github-homelab
  namespace: renovate-operator
spec:
  discoveryFilters:
    - Peej11/**
  extraEnvFrom:
    - secretRef:
        name: renovate-secret
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_HOST_RULES
      value: >-
        [{"hostType":"docker","matchHost":"docker.io","username":"$(DOCKERHUB_USERNAME)","password":"$(DOCKERHUB_TOKEN)"},{"hostType":"docker","matchHost":"ghcr.io","username":"$(GHCR_USERNAME)","password":"$(GHCR_TOKEN)"}]
  image: ghcr.io/renovatebot/renovate:44.77.0@sha256:08abfb69f44e31ac9e0e4f438fe4947e517bb425126f5f3b0e4daad8c28908b5
  metadata:
    labels:
      app.kubernetes.io/name: renovate-job
  parallelism: 5
  provider:
    endpoint: "https://api.github.com/"
    name: "github"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: WEBHOOK_TOKEN
