---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github-homelab
  namespace: renovate-operator
spec:
  discoveryFilters:
    - Peej11/**
  extraEnvFrom:
    - secretRef:
        name: renovate-secret
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_HOST_RULES
      value: >-
        [{"hostType":"docker","matchHost":"docker.io","username":"$(DOCKERHUB_USERNAME)","password":"$(DOCKERHUB_TOKEN)"},{"hostType":"docker","matchHost":"ghcr.io","username":"$(GHCR_USERNAME)","password":"$(GHCR_TOKEN)"}]
  image: ghcr.io/renovatebot/renovate:43.211.0@sha256:836919a9bbccc7d98a9280c2399bba2f036678b25d7bd346de5131d374cb95bc
  parallelism: 5
  provider:
    endpoint: "https://api.github.com/"
    name: "github"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: WEBHOOK_TOKEN
