---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chartRef:
    kind: OCIRepository
    name: reflector
  interval: 24h
  values:
    replicaCount: 2
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: reflector
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: reflector
              spec:
                revisionHistoryLimit: 3
