apiVersion: v1
kind: Secret
metadata:
  name: openwebui-config
  namespace: openwebui
stringData:
  WEBUI_ADMIN_EMAIL: ENC[AES256_GCM,data:Mm63ACqCUJnbi8Qu9paR,iv:c7uNvtoNE0EH12PAzr/2WjXxhQJli+6sqQy7bshuV2M=,tag:kSlPAabwyRe4fitgUyl+ZQ==,type:str]
  WEBUI_ADMIN_PASSWORD: ENC[AES256_GCM,data:0iNxitS7rVtjzP32+2DIMDSpnlI6BGGzWqXaM9T1fSY=,iv:+lm71TWeeMyxlo/biAJPxUsgoOtupznuwmvgjtaOzXY=,tag:nruK4Vtek5rFeamsLNgvIQ==,type:str]
  WEBUI_ADMIN_NAME: ENC[AES256_GCM,data:1LGT19A=,iv:WCJtlcUa3NuQ7YLTmMBIoWKkcx4eSc2u7b9jXGT86eI=,tag:TKICzp2ejs667IaBhH+cfw==,type:str]
  BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:CkaTkukIeG6RoaqK1Z7q+h4l7v6aMT6FP7UTThwPiQ==,iv:0Jj97vCSTFM5TI5w0Xstq1I4Ox6pY06DF/Rhlu7aP18=,tag:7Oo1YzaZ4Yx1XnALHkZnOQ==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT1JCNWxnL2MxUUJwRjdG
        UzU5dmtNaW9hbDZ4dFpCQ1ZIYUJxZ0dlVEFNCmNvQkNUOGFpOHZ0Y0c4YzZoKzBh
        Q2xxN0JzRWUwNlJ3L001VVVld2U3UkEKLS0tIFdUMU9DcWdUUVZZTkFjc1BCbFBy
        SUNsMWNaZ1NBdkMwNnF1dFdKeUpKLzAKqGC/4xefS/0tji7N7rJq0nzwKHConPXW
        8QEsLLiIrmFPxvp0KvKwjV5eJWRwWpJC7XlRjdVtlIQKYOayz2xtzg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-24T00:20:25Z"
  mac: ENC[AES256_GCM,data:UpMkIDbtZI/dLlQVwSb2GsmNnNXsJ/gWqXZthy4SjnFAN9HBs+jxJMFf0QJ6j2Gmvra2Wlonw9Z/D4y+ZQ23FzfxrM4zzAQPWQhr2utkY3b8VzNBzLtqy2asi7ffuE5aW6Fx1oRzXT4z5mb/Ebi+rxa9J/vepFTWhvYWx/hDzGE=,iv:e0NUMQtcua9oBYOdz5aW8+CF3yb3UTyAhiaVIDjCCX8=,tag:BAgCe6zbtHt9KX/7Y8OGRw==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
