apiVersion: v1
kind: Secret
metadata:
  name: openwebui-config
  namespace: openwebui
stringData:
  BRAVE_SEARCH_API_KEY: ENC[AES256_GCM,data:Dw//BulkvAMug1AIlhXU0eqZDhPg9iPQJGwFmOXbdQ==,iv:caVBm+2OTpeUh4uZIEXORG55LRTkfr7/EhOe0x4Wkik=,tag:dzAO4P5O8kyFTPDtNBG2Tg==,type:str]
  WEBUI_ADMIN_EMAIL: ENC[AES256_GCM,data:bDUs12H9J5SKS3ZhCXMv,iv:bDxleRaJo+pPeb9lXZXX0KFqwCUUB/0LT/9M1RfvXS8=,tag:Ws/jxUsyWA7f/Spla03Eag==,type:str]
  WEBUI_ADMIN_PASSWORD: ENC[AES256_GCM,data:f392oKd8CWHYkVcmonOM9WOXZ0V5l/VlE7umsfpnQ2U=,iv:om48v4Ui3bep3avQilVu8M56Mp1+wUlzCqvXdVKbo14=,tag:0CmDoxNSb9ZczOFUTVO5Mg==,type:str]
  WEBUI_ADMIN_NAME: ENC[AES256_GCM,data:uCcCllc=,iv:nhs+PQpEaIQKE8agRYkeEcF6x52KYalgcCkBtu6NLqs=,tag:uwWvvQr5EE7v69d5tkZJzA==,type:str]
  WEBUI_SECRET_KEY: ENC[AES256_GCM,data:OhhWUC6tLZZ7B0qYlnma+g==,iv:d1WLymGd/uVFAnxDMOflYYdyYeiOaSLaQFLOGcahc2E=,tag:MI8jmP0snYuB1i41ddQ/mA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQlNIOE5xNm8wVUdicUdL
        R3JUdG5ZZUo2eTlZOEZLNG9nTGtpdE8vMENBCmd3ckhncEtjaHF1QWtaTVMyZjZ6
        R1lkdU14MnBzVXpsdFEveC83d05OM2sKLS0tIC9md2ErME5vTE9pRU9ZbzdFdytJ
        M0tWK2owSTNNNDFMbk0yeWV3UHZTVDgK0CnPtzQdlJ3oj7BIfJIBInZONGyjp28n
        Ehc2h1S3Oqm7hVmhrooo5XcxTr0jbFtIQj9qDLJDs3ACaosL4rCB2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T00:59:29Z"
  mac: ENC[AES256_GCM,data:kBwzYP0N4GGiroQnezVMSvSt5h1DY8JqQsQKeFJj1SXaG/dmdsJt8snOzHLRxpFVQx/LWtQfTROFhBSbg0ToFm5Hc/3H8i6tQHql6Q6ZLAFIGpH72nGMeHZab++bv0NacqrYVkz5vtrG/r3+CbIxGknV4xVbbc3O85xyv25MlZU=,iv:6Jg8G+z/q+KUoBwrV0zSfvfISUMQC7fBK3xxuk2OM3k=,tag:yZ03RRaRFSxUE5VMfHVLNg==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
