apiVersion: v1
kind: Secret
metadata:
  name: openwebui-config
  namespace: openwebui
stringData:
  WEBUI_ADMIN_EMAIL: ENC[AES256_GCM,data:ticKcl8Xsn8zp3tatQC2,iv:A3u6acz71FIaVNae/Y8YapzuLc/dDJZoeIXRrmth5zw=,tag:2biqeiI8ApCO/8sR+hn/MA==,type:str]
  WEBUI_ADMIN_PASSWORD: ENC[AES256_GCM,data:jF1ROrDj7o6w4zoKOOD/hxkaKrWpHxJOi4A37EUzqZc=,iv:E3faSHUS0HJb3X9mU4Kd1njijZyHRMMeglaTZiOGZd8=,tag:KCUDG4HbCHlOQEqVnuvjjQ==,type:str]
  WEBUI_ADMIN_NAME: ENC[AES256_GCM,data:329jayQ=,iv:KkUBkT0GntX3NtuJepCG5jD187IMvkfIze6Z7rOZazc=,tag:otH221/N5M35GHBc3sJIEQ==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcjR6WFIyL3c1TWRVdnl2
        b0lwMWhBWEVUTndpbUNaaVBZN1F3QWlTWld3CjlWTkoxdXpQQ0RzOCtyQm5EUXMy
        UE5WUnN1Mkc3clNpU08vb0xMcXFzUkEKLS0tIHd0UmhyMUtza0FvUEJEUlppcW4y
        VlEzT2FIMDFhcVBtUWkxTjdYNGIrK1EKFp+gPF8k3pllCkZA4pqPGdhQzksp6kLW
        720NWsspwWOx5TQQryS2ak/hk6Z0i3ZmkD3BCRpkFMEvgCnbPpvFBg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T19:38:27Z"
  mac: ENC[AES256_GCM,data:PmXRwDm/Al5w03oGHDg0JKYeV7xxrnZq4TkOi1Xn+KVnfPCB55s5HhWRHyCqbHUgk9IbbMKs+CTGPwenCGhzcBUehaIw9BnLTLifwc0aBHNW9WViomMPbmhy4N9tSoioEGQBlFq4vFIFRJpnMqualn2tCQcm7Pe/lHeVMTw4b4g=,iv:MC70pEsZUM2VxP4casDE1fmhRCt8SIPxj2CO02kLcqg=,tag:migh+QSGHB8ftF4t9hvuHw==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
