---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worn
  namespace: worn
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: worn
  template:
    metadata:
      labels:
        app.kubernetes.io/name: worn
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
      containers:
        - name: server
          image: ghcr.io/peej11/worn:0.10.0@sha256:c78e3376c6220c189412892a6507ea5b6073fe534c2cce94cda9f22333db4569
          imagePullPolicy: IfNotPresent
          env:
            - name: LISTEN_ADDR
              value: ":8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: worn-app
                  key: uri
          envFrom:
            - secretRef:
                name: worn-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
      imagePullSecrets:
        - name: ghcr-pull
      restartPolicy: Always
