apiVersion: v1
kind: Secret
metadata:
  name: worn-config
  namespace: worn
type: Opaque
stringData:
  SESSION_SECRET: ENC[AES256_GCM,data:w7qV2cqayt9BagjuvdwP43QHEoCZCgsmtn9RUz9LGoN22J188dIY1DY9SDo9ZkUY96cnn8ep/iqeLUxbawJ99Q==,iv:39F54zGZsUsMFIyqSNAUm5OC8afx38WTAl1SJz3oVQQ=,tag:QQvG1A3IVjVw0MJO3o/9gg==,type:str]
  BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:g4ZPG/J6AYCzSqk=,iv:1DUy3sE204lLam2T8TTv+XZ0vKIKHt+pnZTrSOy/91w=,tag:6cCdhNJDUb563d+dk3QDjQ==,type:str]
  BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:bnQjzEkxKjrn7UT9WMfcVJtf5/7Ljen6NWcZmzvJCpM=,iv:6p3Mk4bSwwPScenyCPDi5Twc1qCneF5Cjusj4hq3WRI=,tag:4eb76uCmEY/rQMZHGmWrKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmtXekpKUmdNZ1BFQlkv
        L2x1UWJ4bmRRT2k1bTBpSTF3YmdBUHVxMVZrCjlmVnc1czdwYS8yQndybWt4YkJ1
        YVN1NzBLSlVUNzRaeEU3UlM1S1dJUTQKLS0tIHNkb3d2T1JneGxlY0RKTEV2aFVu
        Z2lQcGFZVDZOWFZlaDVsTW9qRkN0WnMKmaogJlrhEe6zdKBmiZHm27lTLIrYQmJP
        Y4EDtWuXNqU2MppI18665ZZ7qiUnGACXe3JKtSa/4cAriLAS5udTJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-08-12T02:27:22Z"
  mac: ENC[AES256_GCM,data:ajHFU+w+EZf6trY9PbVSqRzdCditmfJAmRVnufy8I3tCTHYgABdXTQi8KJqMGJCOO91o6b9GXofI5x9QB0LX14MI1iXJsTwaLQojeTPdix17NHouLU5nNB4fBOUwcA/BxMXD8v1Agw6aYuitHpKoomBiIAyJ2e47ZKdGF9t+JGY=,iv:e7hsT7gMChd/RTERah84vfqTxbjMCNE16HN7WoOCXBY=,tag:3z+vIvWoVjSxAl/KW/lwAg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull
  namespace: worn
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:RJOT2C1YjtQOQaNkWhbDyOyhCrYty+wGGCi/sPpv7hQOWsnePNPc8hjdntHXm6L7w0pqI2CEBGPQLonHLp4islnA2rdtVVxdWY7GCrihu9kembTcuotLH8HgFueEDl5swrXnYXqaiCZ0OV+f0v5ktxSIotVTh9NAzrdjO1odVcTQm7SwD/mr5tww2mi7ZRadydNPOfkyb/l4t8a8agtLXDwEQPeiJ2QNtVWEaLdQrBkB8GHZzYfQlXqzH8xqmu4unsfVvGuyN4mZKw7SmWofY7XzVgfWMmVbu1/lQP9Vpo9hgLgg,iv:C63fEMxuRtC515KLs+C60OW3s9SoNO+Y5o6S6pW5ViQ=,tag:MFdBJE4IQW+A5jgnhH9L7g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVmtXekpKUmdNZ1BFQlkv
        L2x1UWJ4bmRRT2k1bTBpSTF3YmdBUHVxMVZrCjlmVnc1czdwYS8yQndybWt4YkJ1
        YVN1NzBLSlVUNzRaeEU3UlM1S1dJUTQKLS0tIHNkb3d2T1JneGxlY0RKTEV2aFVu
        Z2lQcGFZVDZOWFZlaDVsTW9qRkN0WnMKmaogJlrhEe6zdKBmiZHm27lTLIrYQmJP
        Y4EDtWuXNqU2MppI18665ZZ7qiUnGACXe3JKtSa/4cAriLAS5udTJg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-08-12T02:27:22Z"
  mac: ENC[AES256_GCM,data:ajHFU+w+EZf6trY9PbVSqRzdCditmfJAmRVnufy8I3tCTHYgABdXTQi8KJqMGJCOO91o6b9GXofI5x9QB0LX14MI1iXJsTwaLQojeTPdix17NHouLU5nNB4fBOUwcA/BxMXD8v1Agw6aYuitHpKoomBiIAyJ2e47ZKdGF9t+JGY=,iv:e7hsT7gMChd/RTERah84vfqTxbjMCNE16HN7WoOCXBY=,tag:3z+vIvWoVjSxAl/KW/lwAg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
