apiVersion: v1
kind: Secret
metadata:
  name: worn-config
  namespace: worn
type: Opaque
stringData:
  SESSION_SECRET: ENC[AES256_GCM,data:gLZt3lLbad61ardra+0uZJg37yfXL4AWIu5kcnSS/6U9e6h9+IYKPpihy6soBpzb9wDxyOCBiK6Zxjc/pH5vbw==,iv:Q3doNQ9sCuxeIODAVbXJ/BhPh80P00DpMUHpebY5gak=,tag:Eo8hrP2ecPxdhpPy5xPkBA==,type:str]
  BOOTSTRAP_USERNAME: ENC[AES256_GCM,data:ltGQX7CSe6fsEH8=,iv:Cf3kl3Pna5rx7bnl6YKhVWjzaYEUvfctCsRu8G/xqVI=,tag:tiIresSHrFSZY7Ey/ozP/w==,type:str]
  BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:OWV/fCrI8dOzfI9FVYgQ5yQI9AVNegjOaTDjV/TFTdY=,iv:1jopB+JNvMHbNGdbIp3kOENlZwEnzhw8/xjaxwVv5GM=,tag:p0kGb+KGGqLXZvya+UjKww==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UWRKV0N0SGgyRHpydTJB
        MjNETDNGSDlWVUtSTzJ4N2dCRmphZ2M1M1E0ClBNRGNyaG05VFZ6cjl5RStpWDhX
        TXpZdDJuM0FLZDNoK05ONnl1SUpwVkEKLS0tIGhzdTFkSld3cDlBZFladEduY1Yr
        RURKTHdRKzJCYkw2NFJXNXBNVXkwV1kKxW1mB15YxVSSJ591i2aCbSOZJIHhllS8
        owZ877IyXnO3v0+JokIaouuYJs8XZ6mijTQN0Gk1KzAze9dy4jE/XQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-05-21T00:39:14Z"
  mac: ENC[AES256_GCM,data:ozyrhhZtdRdInqIaWaDyG2qM1H+j0661fm49Rz42nBtYmjeWrwYPF7FwzcVgSlBI8M9k0vQ/XvWXXoMCFlj1oiLE+XNwMvV9HMnFgOlsBnaaNvTrscKtDUjGyv+4EyLJvjtIwzty6Yim7so/DfGoqT3Dfaex7hQA1r6ieWLL+yw=,iv:hqz7b/xu01kQWJU3uok9T7drcYusvxV94dTj8hwbrSw=,tag:pFzuX+IffFAF6GyMhsAMkw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull
  namespace: worn
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ENC[AES256_GCM,data:6r62YWwUykNdXsc8LGc9+YZzl47fJeYzYqjx1b1/3qKPLupUo7Ni1l99agsWWjc9yk0q4QfaGuDrxXy9ussBEoChJxJLZujOIUWDnMn3JqHymLo9ftqfBGd4toPeUhqi5H3/EGZ79d49iWlY6jXsoS67YL+hfhYXyBXgV8tT/dVCF89v5PgNSTiAxAIPSyPVcXWLqNSWP3hGBg5NS1eKyGSFUfw54vn1Q/Am4HLyGz2FLB4s0GgPo+kB4kaGxC9UXOGIj7/aDlX/JTQV+dWYZTW1LgjPar9JhGG8Bm5rMu2GfKmu,iv:TPGWxGRyJwdkxVuGWMSv2alhxbSV5Gf/3MQvfJNfhzw=,tag:Q3v9DQXbXTsFCBI1VrROgg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UWRKV0N0SGgyRHpydTJB
        MjNETDNGSDlWVUtSTzJ4N2dCRmphZ2M1M1E0ClBNRGNyaG05VFZ6cjl5RStpWDhX
        TXpZdDJuM0FLZDNoK05ONnl1SUpwVkEKLS0tIGhzdTFkSld3cDlBZFladEduY1Yr
        RURKTHdRKzJCYkw2NFJXNXBNVXkwV1kKxW1mB15YxVSSJ591i2aCbSOZJIHhllS8
        owZ877IyXnO3v0+JokIaouuYJs8XZ6mijTQN0Gk1KzAze9dy4jE/XQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-05-21T00:39:14Z"
  mac: ENC[AES256_GCM,data:ozyrhhZtdRdInqIaWaDyG2qM1H+j0661fm49Rz42nBtYmjeWrwYPF7FwzcVgSlBI8M9k0vQ/XvWXXoMCFlj1oiLE+XNwMvV9HMnFgOlsBnaaNvTrscKtDUjGyv+4EyLJvjtIwzty6Yim7so/DfGoqT3Dfaex7hQA1r6ieWLL+yw=,iv:hqz7b/xu01kQWJU3uok9T7drcYusvxV94dTj8hwbrSw=,tag:pFzuX+IffFAF6GyMhsAMkw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
