---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ns.yaml
  - ./operator/ks.yaml
  - ./models/qwen3-5-9b/ks.yaml
  - ./models/qwen3-embedding-0-6b/ks.yaml
  - ./models/qwen3-reranker-0-6b/ks.yaml
  - ./alert.yaml
