---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sparkyfitness
  namespace: sparkyfitness
spec:
  chartRef:
    kind: OCIRepository
    name: sparkyfitness
  interval: 24h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: sparkyfitness-server
            patch: |
              - op: add
                path: /metadata/annotations/reloader.stakater.com~1auto
                value: "true"
  values:
    global:
      storageClass: "rook-cephfs"
    config:
      timezone: "America/Chicago"
      email:
        enabled: true
        host: mail.smtp2go.com
        port: 587
        secure: true
        from: sparkyfitness@${SECRET_DOMAIN}
        secrets:
          existingSecret: smtp-config
      garmin:
        enabled: true
    httpRoute:
      enabled: true
      hostname: "sparkyfitness.${SECRET_DOMAIN}"
      parentRef:
        name: "envoy-internal"
        namespace: "network"
        sectionName: "https"
    postgresql:
      enabled: false
    externalDatabase:
      host: "sparky-rw.sparkyfitness.svc.cluster.local"
      port: 5432
      database: "sparky"
      auth:
        existingSecret: sparky-superuser
