---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sparkyfitness
  namespace: sparkyfitness
spec:
  chartRef:
    kind: OCIRepository
    name: sparkyfitness
  interval: 24h
  values:
    global:
      storageClass: "rook-cephfs"
    config:
      timezone: "America/Chicago"
    httpRoute:
      enabled: true
      hostname: "sparkyfitness.${SECRET_DOMAIN}"
      parentRef:
        name: "envoy-internal"
        namespace: "network"
        sectionName: "https"
    postgresql:
      enabled: false
    externalDatabase:
      host: "sparky-rw.sparkyfitness.svc.cluster.local"
      port: 5432
      database: "sparky"
      auth:
        existingSecret: sparky-superuser
