---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: sparkyfitness
  namespace: sparkyfitness
spec:
  interval: 8h
  provider: generic
  ref:
    tag: 0.16.5-2
  url: oci://ghcr.io/codewithcj/charts/sparkyfitness
