apiVersion: v1
kind: Secret
metadata:
  name: smtp-config
  namespace: sparkyfitness
stringData:
  username: ENC[AES256_GCM,data:1k9g1H4UN8DJ9dYfKQ==,iv:G52eUVVabc86QyalrIRySwnSvrT1LGKqhNbzxnu3GzU=,tag:OKyfDmJdDsGL3Sarl2lmrQ==,type:str]
  password: ENC[AES256_GCM,data:b+/99WBiT3MgnX1TCIDeKA==,iv:nX2hxV2dMwGiVr5qPKyjeuZtPr/Dx1zncLt51mLEkI4=,tag:SZttnvZNcHwqI6Ft9k8L4A==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjWjFVQ2VySmRFV3RYKytk
        TG5YN2xFaTg3YklnY21ucEtqMXVjNWp2QW1ZClVLZmJZbVI5Q1RraXd6dmlKc1FX
        Ti9oV0RPSjNwTm5vYXNzNHlhVlRZWGcKLS0tIDJqKzFXSUhWdEJDYmhXT1RDUlVG
        N0ZTMWJVRWN5Vk9mbEFYbHI4aGliMG8Kta6lYeM5SsD+Eo0CWAILvs1hs3NoW1iC
        //EdnpKRBuumu2U4uF3ra6mlW7ILvXjokXslcP4xZ+I1apwSqR6K5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T21:47:28Z"
  mac: ENC[AES256_GCM,data:1zGHrnmAI0qqYXDGZFp4E79MPDaP1+5gzB3R/GBT9mdUW0v6Sh/cJcGYNS85/d3+CvibtNqrW3109+zSWF6E47o8ZMSj9ZHoXaLtTsHvXNr5N6kC4+SDzz8YkMB1+8ULuwsMvpvPyWPCVJoDB8xcBA7OGyNG2e1OlHToLg+mmOU=,iv:g0vcZknPsJY8nDJ2clRzi2gXxqYitkd7wB2zfpZwPMI=,tag:T9Sufmk/rTn7TR+lNeisbA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
