---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-smb
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  volumeName: pv-media-smb
  resources:
    requests:
      storage: 1Mi
