apiVersion: v1
stringData:
  username: ENC[AES256_GCM,data:YBc9,iv:qWNjZpNMwbDZKTJlDG3HljFTPR1smx0rAd2yyeUIcD8=,tag:fZCDP0Q/vN7Rcjqjs+cP+w==,type:str]
  password: ENC[AES256_GCM,data:GMM+awA0ZtPMYOc0MHDcRud7do0Z3gx6NSlO+egk,iv:dIR6hDHiPYu2bhcdFgJAbq49c4NLtuoP/xlff1XJOgo=,tag:nxYHEI2bMFJ8PuQzO7oIyg==,type:str]
kind: Secret
metadata:
  name: media-creds
  namespace: media
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDVWFNZS8xZ0lxVG5EaWxr
        VTlUVExTWnpPL0NjaTd0YWkwYTdUWlZkTWh3CkVUUXpBU1NHMDBVaGNwQ0JNd2JB
        M3hoLzNTc2tSbzJYSENKQS9leDY5akUKLS0tIGZlY0Y3VzV6TzA1Z3BXTEdRR05K
        elI0YzBLanFrVDRVTlNTL2p0VFpxeXcKeSFN4A2uqIMdL+Zxwn4C1DYAXNjaBnQy
        Cpwlx2fQSOLv3ObykzJZCc2bvxEhRJb9n9bSnC2a61wBJTBRnJZRVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T01:21:17Z"
  mac: ENC[AES256_GCM,data:T06Zlg2dmNCJ8AH3RZKpStC63NHjEeezZvjxSWxCPTJwsKSsammD0HDErXxhmMLDXLpW/3CqCj3qk4ng/bpNOnPViJilYIIfIu3JA6Eac7DyjVULOYeliol/WCz23IrRyyM2KTDn9+suzf9D23q9b0u79OwBzX/qTzRHiuSEjhA=,iv:SuBrx3VR38dGaETqKN20hSiXBpe0wAQPpnnCDQWfxQ8=,tag:2EfqK5mAboKyRfyF1YiYpw==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
