---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tuppr
  namespace: tuppr
spec:
  chartRef:
    kind: OCIRepository
    name: tuppr
  interval: 24h
  values:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: tuppr
            topologyKey: kubernetes.io/hostname
    replicaCount: 2
