---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: tuppr
  namespace: tuppr
spec:
  interval: 8h
  provider: generic
  ref:
    tag: 0.0.80
  url: oci://ghcr.io/home-operations/charts/tuppr
