apiVersion: v1
kind: Secret
metadata:
  name: resume
  namespace: resumes
type: Opaque
stringData:
  identity: ENC[AES256_GCM,data:nqwHrxptXr42LkirimjIJs6SiDeLJoSdeSY9DrK0EOyJJ7bW5XeHXoRXEit7OxGmnw7EgLxW/PT2kpnLWPpbtzX4Mc4GuZIi6Nrp/9//JmhYX0JKcj0oWs/tXZkobOOYNcBIppVg8UoiaLjSOQpFZF9luYx2+0/He1DscqDrP3sdcZip2fpbqZG2y37+EwVI8yNMKOAx4CXg9/0NuMCYas6DYh1ECG/WbRLlvPVVZfAZPlROSbnuhOqO5WWcbUGCbaHr7Q8MVH6M1Fjw90CTRH04yDRF1h4OTC4ta1z4u/EZi8vZDgwVPTTjX7gKBxdOFfCOVzQBHpt2DoGsLCMA84FcTFbtTAlIj9/oCMfyKexHRAMtiM2/N3MXDRrklyZ0MHWdZM99lmC+4YNti9YorWGJtkFrnlzoI71zojDDU/JGMIv1oaC5S0OreVULQyI0hIr9z7izIk9M/WJSpcOuNN01cfcCmtgsCvWpkSohkvlEMMxmLy3zY579VMHIKIdja6Cn6q80vIext1Acqm3i,iv:Uq6qeb5DbDD3X7+e3NJS05GJM7lleB2bnTR6Du3AmAw=,tag:+cw3KBBpAgS/DuuQ0nfXsw==,type:str]
  identity.pub: ENC[AES256_GCM,data:eyCFXPiF8G7xPS3nsKgSM2nzHARTGrzFmKH0SL37K21MDIRb4uHYPq7FTgfXFk6iUrkbifUL0QxP6e2ENTsAwUq/N/cCbWBcxKct/pRpGPVg,iv:OwhJsur9Q424CfmZzaqB/jiB2I1P7PyOuo3Uop6JTO4=,tag:7zjTO0Ii1v47Aue/ykYiTQ==,type:str]
  known_hosts: ENC[AES256_GCM,data:TNdfh0KEOM/aBGOW7xQY34dA0dGmb/6CJ0Aton/uhu2eP7/P4dJOzSSxgzeDQXzGr0qcyBOIb/uvYUhYuX0YRuZgPEp8lpu80k48jdS4+xFw7a8ryQG7LhIurfXIVpQZ7u6zWrDHpuMfn4g/uXNHFHFInACPlgpC4in+5hEKDSFqrf6OaS495erCcx0w+35uBvSbjz65JIYyNiOWIxYSsqjIEL3HSfxSRlyiDQ==,iv:5YIu0tDoCPrgPLaFR9Bg8DmPY80FGqJYZes5gnEfEwk=,tag:6yK2tBx+HOjLma3rKW2pmg==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZXAvNjlEQThsNGNDeHZx
        OGJnT0tRZU4rRnl1MHFJQ011R1dobElReXpjCm1abzlkeGh0K08weHUxaDIwUWpI
        UXRNbnlMUnI5Y1NnajB5RTNHR2ZaVGMKLS0tIDFHSlZ4Q1R4ZUNoM2pEalhNL2Zr
        UVB5aVhudXc2Q2h0N0pLdkZkZUNsSEkKmsyNjaTNbYMdUHWxVL0DmbNIlCXKeN2n
        RzVnhLQkfj8TBYi+hYsDkzNg0P5zWVbSKc0OkJIxk4l1EAhqm9ylzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T20:34:05Z"
  mac: ENC[AES256_GCM,data:9aaKerzyuWzn/EKjggDpZR3WQj+NTy1nBj3JVhMEhJUiWIlswoObtAlEUTmux2jEy6nzzfTvu6JXSm1HfxmZCf61ZV0skJ/+LfIRBwkFZQQ1I5kGvzLXZJ1lJA5xDyt+TCTsfX/RdGu8idLq+iP9te4nsmsR5LlYQIBH2JL2SWc=,iv:+aUJIcggx73aeiZoFIF7kUqr4LPfnjlxYTtt3PML12U=,tag:9N0kcrtnmY2V9/dmZ0CSxA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
