---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: media
  labels:
    app.kubernetes.io/name: kavita
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kavita
  template:
    metadata:
      name: kavita
      labels:
        app.kubernetes.io/name: kavita
    spec:
      containers:
        - name: kavita
          image: ghcr.io/kareadita/kavita:0.9.0@sha256:36aab0c578d488f8b10bd33910953b50965aff9ac6adc476ef4692c38c60427e
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config
              mountPath: /kavita/config
            - name: audiobooks
              mountPath: /media/audiobooks
              readOnly: true
            - name: books
              mountPath: /media/books
              readOnly: true
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: kavita-config
        - name: audiobooks
          persistentVolumeClaim:
            claimName: media-audiobooks
        - name: books
          persistentVolumeClaim:
            claimName: media-books
