---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-config
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 5Gi
