apiVersion: v1
kind: ConfigMap
metadata:
  name: homeassistant-configuration
  namespace: homeassistant
data:
  configuration.yaml: ENC[AES256_GCM,data:KIujMdWNdHjKIz0DIaq3fwEspl+CAE7iELNNY/ehaFBGr9fR5FNRgpo9Xb0TTIUk5Gp1NbfiQunwuYAIxEHs5PTsSZLcOf7Fu+aHIXIKKww9W9a11MLw5A2FcfuDdqiJttvP+O7Fk2c29Q==,iv:/lxpQjrZK/aCUa/AQOONC0i9k8CycJ9mDXDbpXH0vYQ=,tag:e43smI7DKykywKPByQTwzA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaN2JwZW9xSStLaEdFNGh5
        UHBJcTFhcEkraTlhS1FJNFYzUHl1U08wN25nCjV4dlpRSktOcDZyc0NlNFg5Mm1B
        d3pGTkEvSkxnUnorRnl1UWI1YWszMk0KLS0tIFJsMXBGaFVsbXBLN2NBemE4Ly9F
        eFhKbWxlWHdxcVlMRVowQUJnRUdjNFUKtClocrluQQgAN1T0QuUW0Ht3PUBC+bCa
        N9nalns4eU2HdNDSpjHMzVrarkL9XTZ+rhgl4lSLwFkrBofWpgxcYQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-08-12T00:57:44Z"
  mac: ENC[AES256_GCM,data:N50tdzIuZljDcCPm6AkgFhpF06wdw8L66ywAjLTOtDuuODDMSftqGz+JlrND0wLS8fIRL/sshZpvT99a+752LSXCOVpAzS+1ifzBZNrJD0qX+2lEwX6b679sYjQ9cqk/82onzYMmowX71fanZUY3YkQGUZRXCcubd3Ukpa5Gg30=,iv:RgIWq8u6jyyFtGf/Rv3cpyjWIOWjnJ64f3Kaiv/AC4o=,tag:qqLBO0guVkC3A1u1u7dq9A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
