---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app.kubernetes.io/name: homeassistant
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: homeassistant
  template:
    metadata:
      name: homeassistant
      labels:
        app.kubernetes.io/name: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: ghcr.io/home-assistant/home-assistant:2026.5.4@sha256:ceb1202133a5a036e8b03e20a10eb113186cc2f871968323c6fc6c3fc4205716
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: "America/Chicago"
          volumeMounts:
            - name: hass-config
              mountPath: /config
            - name: config-file
              mountPath: /config/configuration.yaml
              subPath: configuration.yaml
          resources:
            requests:
              cpu: 2m
              memory: 750Mi
            limits:
              memory: 750Mi
        - name: zwave-js-ui
          image: ghcr.io/zwave-js/zwave-js-ui:11.19.0@sha256:0a363b3aa06f76c3c2d24fbc4ac5aeafdd993ee3f63a4031c207c07f15cd46aa
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
              name: http
              protocol: TCP
            - containerPort: 3000
              name: websocket
              protocol: TCP
          resources:
            requests:
              cpu: 2m
              memory: 250Mi
              devic.es/zwave-hub: "1"
            limits:
              memory: 250Mi
              devic.es/zwave-hub: "1"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
          volumeMounts:
            - mountPath: /dev/zwave
              name: zwavestick
            - mountPath: /usr/src/app/store
              name: zwave-data
      volumes:
        - name: hass-config
          persistentVolumeClaim:
            claimName: hass-config
        - name: config-file
          configMap:
            name: homeassistant-configuration
        - name: zwavestick
          hostPath:
            path: /dev/zwave-hub
        - name: zwave-data
          persistentVolumeClaim:
            claimName: zwave-data
