apiVersion: v1
kind: Secret
metadata:
  name: handbrake-basic-auth
  namespace: media
type: Opaque
stringData:
  #ENC[AES256_GCM,data:XueBBTlb7ZTlUQYSDyVbsqbFmxG9z4SZzw==,iv:dParL15Nupx85tSUBA6V1RefgT/EDVf0gloC97RJrHc=,tag:x1DaU0r50amRqQS8dFZYag==,type:comment]
  .htpasswd: ENC[AES256_GCM,data:xo+NHuEOOsPK9d8zgVe/rXnZAIigGa+ORAvbJyQa7Ug29O7bFYcOx8twzjRf,iv:Fo3Yi/CQvl0uPJOMtGQdtfI0UZGgQQ8HiH8b8lxVqr4=,tag:dAWf5k2AJ/Qc0g12j0uRog==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwOElUZjZXN05obGp6eEVq
        VmZ1L0MvRm5taVBPcVRRR0hnWlJvUGJiTlN3CjJmVENEeXlSZ29TOEo2TDZUYVRX
        OUJiWE51eVVHdDR6Ny83aVA1eVdSbEUKLS0tIFJOYUpKaHBWKzFnT2FMTUxnRHZB
        d2JCb2I3cjRjMDFzeVVaTkRKaTFpWVkKeUmG1kja8MxhvWVuMo/rsAX/DLemWNFC
        I9QKBHqj/ryZ1XaVCyaasjiT8FGHKT5d04C6m2hhkVMsehC11mjkpQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-06-25T01:58:40Z"
  mac: ENC[AES256_GCM,data:z6CnQnJSUMBkohGrwCYSSXrKn8C2N7IZHQLB8BmtlIIl53Eb29gLFWbV1qluHq7zPP2844T0I858LhE2YnZ5XNgWo3wInO8JWNxUW9N1hh/T21/nLiR3x3BaTBiCYKk17bzEERWOGekXB5NY4qfs7bfuh7lU/gr1zmkpiD9AZ7g=,iv:d8RlXqX+ZIo904TLoGIUlgp7r3ayK8nEO877hexHB8Y=,tag:9fcIdVVz7rbva9lG/k+VtQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
