apiVersion: v1
kind: Secret
metadata:
  name: valheim-config
  namespace: valheim
type: Opaque
stringData:
  SERVER_PASS: ENC[AES256_GCM,data:ZG738Gz4,iv:TMzxSlv3CudJtCOuKLU339ig63W2+AtkYCHqf9RAcCE=,tag:1LDV6yag1pbrIFd9wuWxRw==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5S3d1aklEY25NMFpZZ1R2
        eFdRcGVWUmpZK09QclAzcEs4NW1jQ0Z2WVNRCmdkR21peU5jVVBlK1I5TlVVcVZo
        QzNZd3JUYmpSOTdMMjlDenVOY1hGWjgKLS0tIFhudHJtSUhFSXVRaC9VQU83Yk1P
        NzltUnMvNjl1UXhmTy9ySWhiK2NRUHMKJcQ1B1Xse19bDilTH037jsgnlNZ30shx
        HTt89sSd9bYCJdz0ur/EwUchRJzCbNnhe8mmmzt+lgdkDnA/9ccIYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-23T20:13:35Z"
  mac: ENC[AES256_GCM,data:KUlikwc/PsKIkV6f1SnU6AgjNuzvdcTX/AC1OsqqSARs3QnOjWMAr8qYQ45PH3wpS3mbc0uzTxiA2lduRccmYoFrAEVC7D6MuJtD/IwvI93iXT9WqNCSTArI1+W/e1bjEPPK2BSDZXyiZXBU7VlFAShYfd9QGMy5MNucPTNbIL4=,iv:W9xRB2JhkxXCm38xcxXYAxIEOZ5Vc0A8+PWM30w34pY=,tag:O0W41f2QV74EKjmB5OepHQ==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
