---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate
  namespace: renovate-operator
spec:
  interval: 8h
  provider: generic
  ref:
    tag: 2.8.7
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
