---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate
  namespace: renovate-operator
spec:
  interval: 8h
  provider: generic
  ref:
    tag: 4.12.1
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
