apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github-homelab
  namespace: renovate-operator
spec:
  discoveryFilter: Peej11/homelab
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: >-
        [{"hostType":"docker","matchHost":"docker.io","username":"$(DOCKERHUB_USERNAME)","password":"$(DOCKERHUB_TOKEN)"}]
  image: ghcr.io/renovatebot/renovate:43.25@sha256:45a8346c40aad0fd0b10dc685821b344532d88f9cffeb597079bee9d21cf1e2c
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: WEBHOOK_TOKEN
