---
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: renovate-github-homelab
  namespace: renovate-operator
spec:
  discoveryFilter: "Peej11/**"
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: RENOVATE_TOKEN
    - name: GITHUB_COM_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: GITHUB_COM_TOKEN
    - name: GITHUB_COM_USER
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: GITHUB_COM_USER
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: renovate-secret
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: >-
        [{"hostType":"docker","matchHost":"docker.io","username":"$(DOCKERHUB_USERNAME)","password":"$(DOCKERHUB_TOKEN)"}]
  image: ghcr.io/renovatebot/renovate:43.91.1@sha256:63e27dd3ed7dd5feb755e0f3c8e50516f5845be124311b4f6b3c898b5d767b49
  parallelism: 5
  provider:
    endpoint: "https://api.github.com/"
    name: "github"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: renovate-secret
        key: WEBHOOK_TOKEN
