kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: renovate-secret
  namespace: renovate-operator
stringData:
  GITHUB_COM_USER: ENC[AES256_GCM,data:lxylvFoFREzJ8D0LPj4mihRgi/T327y4RdTRMXxmNox8b7yn70jBXr7jIrFKraXQmjlN3ZsGIZlznA==,iv:oGcf3IxOHaZ/Lzf4f1Pde4qhotOQKNSsMTtDEBx8pU0=,tag:0rIkzlJjtaUBHcXn3HtiQA==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:8cHdUaAhiDRYkj+fQuRL9CJCbm68n2vLQgwLZVQ1leOT/EDIuhNcHg==,iv:yUJGD5yjtC1Wy9P1qHlKXnbTgizWvAD9TBsLbDZym5w=,tag:yp8Y6gu7zA0Ly3u8EUlYAw==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:fpCNI/OMxY72ur23rHF5xuQWWZEGhuhm2LgXx14WSyhndP4sK9L7sw==,iv:fI4lPobFO5Ot7oIMX/qVoaV/pv5xH6FDhbpbueD1BgA=,tag:JIMUM9cFdyA/C3+kArO5zw==,type:str]
  WEBHOOK_TOKEN: ENC[AES256_GCM,data:WowmDzU6s4VkqDCaMvRWczWaaFFXv5GPwcBfcWxJVNA=,iv:4w20VeysKoC7hjs6mskzVZNYx23kLLrno3m5l0JrLRI=,tag:NGFl1g/7CtptjcLGCH/Wvw==,type:str]
  DOCKERHUB_USERNAME: ENC[AES256_GCM,data:1BD8yG0LWdAZaL0=,iv:xY6vlPx+Juywf+vsKc4DhHbNla4Ett94h+leiBilfZo=,tag:RZxK6wUgsIOkuX+j5n8TsA==,type:str]
  DOCKERHUB_TOKEN: ENC[AES256_GCM,data:fL/N0x6Jrl4TQcy/DmvX7diyJCVi+srH36P392zY+izaZ75T,iv:up+P/o0Cos3YQhHw6ySwYrtsayPIKtbL8/jmLBpXi3I=,tag:Ki23UX30c56LvJUOiUebMQ==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:maWuDJ3nn8iBWHRdCr+GglvUx1SkY93yFhEcxClvJINu4g9ghYwi8EBR+ZE5xRhpAP8c8C6RTamqqQ==,iv:0yh62Mfb4bT2ML9RXP6l7xJi7wf5u5c7bph1b5fEIDQ=,tag:H3PWnCazmF5tiE8vYWK81Q==,type:str]
  GHCR_USERNAME: ENC[AES256_GCM,data:AbVzX7+T,iv:78ASuHL37rg5T5iQSEg9AJoc2V7Hzx2jQNlpBZsLxbc=,tag:1RkT01y3oSi8VVUIPbtwjw==,type:str]
  GHCR_TOKEN: ENC[AES256_GCM,data:PAUeKcJWmyLvLxrRul1ykvka817Ih4K8/C30I3Uv++6beYJhxNO+lw==,iv:rYhJ0TF9UFluaG2JZllaMKmCOgrcpqK1wL2fA67mZ6Y=,tag:IwQT9OBPB/IJgoETwgpBXw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVHF1RXhQdGxzd2xhTWN5
        RWhrMUlRSFVmdmdRTG12NDlRdXVpOFhyRldZCklLY1BYNUZRWlQxUmlIbG9JSFBp
        aGxOZW1ybWN0anZRbmF0b1kzanQ1WkUKLS0tIGdMbFdQVUJONEpUQmhsUCtQb1Jh
        WUNJYnBESEUrR0wzcVd0ZDg1NDdMSzgKsQeTusM72rtHN1O6ylWW2iT7u8PDEPgj
        TqlPPBiNd8tg3FQBSL5t2OVIDw909EzW3u8IPAtc5xOPhS5WRReP0Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-05-19T14:38:14Z"
  mac: ENC[AES256_GCM,data:QUC3Ba+y8351QvB427OVmgjvfLSAX1M91qv2dHIfSTIiuutJr3jZXiuVCjxff8dD6jcZvMzq//7Lu9YS19hCcN4xeNrr3DOObc1wn4zpSRdO/apdJ66Kmdyc8UgrieAaOko7sg6YWP6AuIslIUCX9JiJHIStRbGURSbBmhFb8uk=,iv:RKlXuKo/rKA53ZkUWguwvrOznOcUYNs5yEuRu3XTyhE=,tag:VfazTl3i6x+2J8PoYH89hg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
