kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: renovate-secret
  namespace: renovate-operator
stringData:
  GITHUB_COM_USER: ENC[AES256_GCM,data:tlv0LYvKeihAL4wZ7YBrAHDClcOPHyxuxWkBGq7YebdnTvwaBaGpmws2PvQHqGNxR7en6x5WD0+/Vw==,iv:zjXQZU5W31teG4X+JDyLNWLb4JampIHkxRefFVUeiTk=,tag:cjq3BME+VMfLkDpdi8SfXw==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:Kbqf6Fj888GXG9k6q2qfYOHVV7OjpdREXFaDHoJcRdS0JSCYvck1ow==,iv:UUXrzpPsZ32KTS4ZBlSyQb5HlI48r5CPAH7yqpiCUVw=,tag:kxR1h6rpMVF+t3GG1z4TmQ==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:V3popEdnebr8ta9SoF1sVAW5Vn1waUtF3Hz+VU29u9QznvBew1Xwig==,iv:jk1c09V6OGumf5WD8b0ZNhFn3UWZg+L1V8MSitFpS7I=,tag:LxkJ7ByHzGV0dVjY1AoL9g==,type:str]
  WEBHOOK_TOKEN: ENC[AES256_GCM,data:hXtukyoGb1ZAUc4ooBPKroYbXKeyzGEaFVueW3vyccc=,iv:98Fg7c4YlFv9X0KBG0NOK1FrFFrBRa2IAO6DpnOQVoE=,tag:fGR/nHFFa2ovYRUNBvfrUA==,type:str]
  DOCKERHUB_USERNAME: ENC[AES256_GCM,data:nmh+f0kT9pNRlsw=,iv:veEFI4/+dlxgrvuOZaYMZxYt4BZXl6RSdzbOCivtu7s=,tag:KMD7ZuyCweOpAP4fSFoCuw==,type:str]
  DOCKERHUB_TOKEN: ENC[AES256_GCM,data:PpwHVYjR0WK/1oE4NCkLGhlDeYAnDl0jJBxAv8ktkWC0oAlS,iv:uMYGSQMTkxaS5p+ndWeanKfHJf6AeDkkBs+dpQ2QNTA=,tag:Hn0Gtuxefe/N+UzXSUmC3A==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:q38XHR4WSGbRKHczap3MyofjxIv/0ZJ2HQT4ihw4dRXYulPMruaBogtjWZ9SqTVipjbk3j5InyIowQ==,iv:jEYeJ6FzzIBRDq+8lwAbQoeESlHrZ3XGHJ8qvhbFHOA=,tag:MlelxoW0EcsHXdGGxI8Bjg==,type:str]
  GHCR_USERNAME: ENC[AES256_GCM,data:SZlIABdb,iv:KRwBqB5+eFAgXgFDpTs1JwXERmGkQGmFXRp4UZWoTQY=,tag:lFfdhQ15lvqcicbSe9Js4A==,type:str]
  GHCR_TOKEN: ENC[AES256_GCM,data:KB+KUxPTXYjYhWofWHYaDhGXHsSAGC04tGj+mRXT++LqZNmU+zvCRQ==,iv:gDt3a4Gbya7WtYGZvaQv9PQ3O23wVozB8rNi1ehGc3k=,tag:QrLJ8kRyXLzc0D7X1emShw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1UW8wT1h4RlFwNlFObWRK
        K2hlQTFMajlSNXBDNm02RTJqWDQyVGVyd2dvCkVtbWlaZThJMnRKbkJ6OFpRemZS
        RFlsVWF3MFFsNDNxT0psSXJ3eHhqR28KLS0tIERwSVhvV2dIL01DSVlOQnh0SThU
        aGxJR2VKbHhCVXJPQXRubm1FdjRUdWsKY9uZ1k+9Mm2XrzBWQQa/CjvrkW4bAe35
        gvF9ee5Fc7NybVOpCsJWdPgM9G7sRR/mXf51vlhepMfPHHwWOuEShg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-27T22:52:52Z"
  mac: ENC[AES256_GCM,data:XDn/EL/YHRriwavjV4YM5PtNbnnyPJUt8jfe9LmDCqqwit/XK6aRdWWPv2JVn9En1EpBxDN3SFBNLTHzKM0M7mGJlwr30Ihb53Ll4hKebqFGrtAzjm2i6YmAtZLhKnSicRMp8hDCQ69bmrpyTBzNG6vXmsdFAhVdGWjmzJvWFss=,iv:JrnBbKZgTJRaKIEhVkMTUifx/srDUmpSd1XVoHQXoG4=,tag:UDrKll5f4bg/H8l6/weKBw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
