kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: renovate-secret
  namespace: renovate-operator
stringData:
  GITHUB_COM_USER: ENC[AES256_GCM,data:51Myun8WHR7wd7V44e9hkImg1nwbP2s6c27lhBQcElL7RSfy18WX+qhG7bdLDSWf,iv:OOAaW5uhCuIRYMKxshqw1j17FZ3ub+vUQPycTSWxOBU=,tag:Nj9L/gUveTsJR0Ww7s0vrA==,type:str]
  GITHUB_COM_TOKEN: ENC[AES256_GCM,data:fq7iB/ImMCM4Nt/3zdDRojLt9Xcn7v8ynyGphoELJq1xjvKY66LYdg==,iv:tXNfe/Wnr9XscT3+lvjD2DvwZw8UQvAqOzM7j+QHqQU=,tag:YFrKZ1LpndtNzGNezK7hFA==,type:str]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:xaqWfMoMkp1vDdTORlYEEYPotkpeNTROy5Bvfa+L6uObJRfpk6DY+g==,iv:bF14pF7C/FG0iNnXb4hZX/ytd2XoLd3vFaNdZhH+P0E=,tag:RBHoK+EKfll8QNkLGKtykQ==,type:str]
  WEBHOOK_TOKEN: ENC[AES256_GCM,data:emDTAZcYLRjhJoHiHZO5MFVCoX3eJhOh/vgu7OEqtXo=,iv:zlCfKT6DwzrTB+/K54G96fnfHfj7gTmm92kP5iKjf0E=,tag:47oZC0KaUPUFm9snf6n9KQ==,type:str]
  DOCKERHUB_USERNAME: ENC[AES256_GCM,data:fsJ+1+YoIhOFmyA=,iv:Wm0a7yRcDcZTDlbZXvzhaesfuoRuOkw56vECQMW+Xm4=,tag:du1LV013QTcg4zojxGy7PA==,type:str]
  DOCKERHUB_TOKEN: ENC[AES256_GCM,data:kIhZQST9g5ya8nM1+R9+J2LveA4kvjDCM3HgU+ywprPPIEfw,iv:N+8xc/QX+ufw2CpZyRd8ckNVDlGCEYBCX/mJdOOXV2Y=,tag:yNBEOwaU5YkhiqOdWKpBuA==,type:str]
  RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:VPawHJVqyshgyP7J8iBRoIMO+j9OsCE/6erWjV/SoCUUlpfm/AE9HjlwikBjxFiO,iv:+PRSIyrLo5z+rFXTmrIGkBgRzSKYJbGd7AOyLLJyASI=,tag:8ZviKRD40FZ4vq8AUQr5Lw==,type:str]
  GHCR_USERNAME: ENC[AES256_GCM,data:3276ihVV,iv:acsUJ76NIJJ6FbS/pWIjqbLgaa77EDZrJKBGjw8FHdg=,tag:8zGyhT0XT35H+qSiZxXmzA==,type:str]
  GHCR_TOKEN: ENC[AES256_GCM,data:QaIZScdqbEV/OEd1irxz6TmtxHu06EGnBSU0hv7Z415/CQQyVkFwjA==,iv:OH6ovUuu2wO/AoY6XCukGNHRLV3ASDt+Snb7YRzTDA0=,tag:GSspEC1ahRK2fNi4KKVR+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSVZsVUxEdGVEbXk4VHdv
        bUJnclBYSWFCOE9aSlJiY2NzekhEUU4zSDFRCmM5N0pnQWVJZ0ZUaEZ5ZkxOOHRG
        cCtRc0pISWlYVk1IeGhMZ0EyWEx3bkEKLS0tIGxxQnEvQzhLaXFENmpnY2xzK3lN
        VjMxQjNGaitiMVBiSW5pVVVuSXlzNjgKlDUQcBKaMoqyaFADTNpggZlBykRbNXcS
        QHtC/QgxLgbfRXT8H5WVrX1ug2wcyfjHYhHlDmj40rTy9X4yA3wVnA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-10-10T17:07:11Z"
  mac: ENC[AES256_GCM,data:sbEl/lpV//Tm7dGy8LkRKGheGQcNvRSZoTACplgkwvGsDcZQA/akNrTI+4qEBkScS2c+h7TbbOnfKw0v96bXvI7Q2LSW5jokSdxHM8Pxca18AxKI4SINnJfxQ2PYWy6CiZQcxK8ssfRTmoSLk5rUdFDYOYEuu31lmCxv/3gGD/Q=,iv:gaR+qpPfuH5O5M1xnbW/CKBe/LjlZPN8Y6vWZY1MPgQ=,tag:MVwel8+1vYX6qqGtCyAQbQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
