apiVersion: v1
kind: Secret
metadata:
  name: resume-operator
  namespace: resume-operator
type: Opaque
stringData:
  identity: ENC[AES256_GCM,data:BnLCt4IrzZhm14KZNMQVQDcHrScGrtp8c8Bofq+XAJmJtqIrao7FmaO5x/PfVnNvxSXtE+sSIY2+D3qXLZkRTSf0ZgvOtuc1gr2dN4pYstRttL20LZcX5R4u4vm/Lg+ONfowfD8xwG3R1M6uzdB1owcihjimaF7XJAu38pei0eGu/Hd4vZDUKpvaQuEbYrvWwE3JAFov26myN9mL3UdDEXfppuEO9LmlrvYCeSG5ktsucmePGZlwwWFsynrhhUawfzp+TjKX42T3VfEJ+OtVL1VDbeLqR0OyZHxVx48mwJJEwnWG4jRkdxciwhF/EYZVAeB7llEcaKl6JVY3oFD9hgB6aaPgi9e7o+5bNTlPjwlvsU13UjrwES1SaM6jdCzMP9F2FtV7maKBt/WlajLHuEUiMFu1BWwPUaG9H+Ixfn7c8Pf1FI6gvqSngXzGmYktA6F0uRbml+0C1cV7+/vMBfizrq0QMMwQTekzuYiOVxknK3IM2lQSw+ivgYrMmMBI0ixaH0RaIaOc/+ixG0B4w47DjbY5vgchENCY,iv:CwbnYWqhaLo8pcpimiupsDRUHkBIMtOCUveStlZDqKA=,tag:bcbfYrBoDxHpBc2BSH9WFA==,type:str]
  identity.pub: ENC[AES256_GCM,data:BKgf4h5Bll6x8CbhrrBjNZYFPPDnCWz0zmnELM6FnMXFRCrvhMmx552oUz3XdVH3T3Hnm4IYpdivwJspAXhyby8JKNP8vuAlnpgnQYp1HlkJ,iv:d6eoDQJMpHSdekqgzMnkwL21ID4XYgQDTOY+gVJDHr0=,tag:kTyWiDVtmM74UHvYyAOxxA==,type:str]
  known_hosts: ENC[AES256_GCM,data:laM97NqUg5RyToHrYSAU8JzbDbAsNlk1yFb0Bu9VGprTF+KQvkSWbLs3hmRxpiXxb8FwLuy5PVD5mCOYZX2NdfSP2cKjyZpRpjrVj903h3I4qiOzzkUtAHY4Qkn6Hv3gFDa8/TD8JnJJ6t1mrv8f4YrvP1g/fv/+61NzZ6XsBGlQHOGXkXJ7/4n7aUXZXL8vDYkwcFOYNCsNCK9L7aADnlybhV9mRu50oqxzWQ==,iv:yxR1p8ojAC4venOL6+DMpH5NQiDJ+/ihEKHMiqSIZ8U=,tag:ykoxUWOcvDUPVUnTdpzu2g==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNjZFbDM3czIvckZWZm9q
        dlZ4L0VKaisvYVM2TjhNUnJqaldiOG9PQW04Cm1VTCs0eUYxd1YwL0lmSXl4QmFp
        eDlPRWdpS0g4ZUx2SVdzZjlpOG1GTm8KLS0tIE05ZmhEdFdPY01RQ1ErWUdEVmJn
        azJ6M1RiM1U0dW9EN3orSWZiRUVUY0EK0l618Q7TXq80acMenUm9lGtZlrnF+Y1V
        Syy8Nan9+jWr8q5dQa5RPdnIZPvAQYUGDhz+q7dkCebPG5sAILmy4A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-14T19:58:00Z"
  mac: ENC[AES256_GCM,data:qfe5Cjzi36WjG36RmdRJreyjWkpq4Kcey370XI7lv0A0lCYCBux30tnuRmjAOUtDL50IGA0NzOEa0lUU8Froj8r3xGaW5BTrA0FUzZIHamxASJlrnADyIDtGTNjzHQd0qOP9xRiyBzrbXKMpafxqKoBwTde4l29ogNLJndE4akU=,iv:Lor3cCaodDrcBq8IU+Ao+JNUCqgT8Kc8ZDf+vSsiIAU=,tag:6qDJ5Y0JCxWdHnBm5nNf6A==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
