---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    gatus.home-operations.com/endpoint: |
      name: "D&D Wiki"
  name: dndwiki-bookstack
  namespace: dndwiki
spec:
  hostnames: ["dndwiki.${SECRET_DOMAIN}"]
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - backendRefs:
        - name: dndwiki-dndwiki
          namespace: dndwiki
          port: 443
      matches:
        - path:
            type: PathPrefix
            value: /
