---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephConfig:
    global:
      bdev_flock_retry: "20"
      bluefs_buffered_io: "false"
      mon_data_avail_warn: "10"
    osd:
      osd_mclock_profile: "high_recovery_ops"
      osd_mclock_override_recovery_settings: "true"
      osd_max_backfills: "3"
  cephVersion:
    image: quay.io/ceph/ceph:v20.2.3@sha256:d195020de02512030118e772cef7859e92904e91eb4cb21acb503f8b94118137
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  mgr:
    count: 3
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  mon:
    count: 3
    allowMultiplePerNode: false
  monitoring:
    enabled: true
    metricsDisabled: false
  resources:
    mgr:
      requests:
        cpu: 50m
        memory: 1.2Gi
      limits:
        memory: 1.2Gi
    mon:
      requests:
        cpu: 50m
        memory: 1Gi
      limits:
        memory: 1Gi
    osd:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        memory: 4Gi
  storage:
    allowDeviceClassUpdate: true
    allowOsdCrushWeightUpdate: false
    useAllNodes: true
    useAllDevices: true
