---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephConfig:
    global:
      bdev_flock_retry: "20"
      bluefs_buffered_io: "false"
      mon_data_avail_warn: "10"
    osd:
      osd_mclock_profile: "high_recovery_ops"
      osd_mclock_override_recovery_settings: "true"
      osd_max_backfills: "3"
  cephVersion:
    image: quay.io/ceph/ceph:v21.1.0@sha256:5ff3692d2f3f4bf47ca7717de6f8f8556440ce3e15efaa680b62cb924eec0541
  dashboard:
    enabled: true
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  mgr:
    count: 3
    allowMultiplePerNode: false
    modules:
      - name: rook
        enabled: true
  mon:
    count: 3
    allowMultiplePerNode: false
  monitoring:
    enabled: true
    metricsDisabled: false
  resources:
    mgr:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        memory: 1Gi
    mon:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        memory: 1Gi
    osd:
      requests:
        cpu: "1"
        memory: 2Gi
      limits:
        memory: 4Gi
  storage:
    allowDeviceClassUpdate: true
    allowOsdCrushWeightUpdate: false
    useAllNodes: true
    useAllDevices: true
