---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/force: enabled
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
  install:
    crds: Create
    remediation:
      retries: 3
  interval: 24h
  releaseName: nfd
  timeout: 10m
  targetNamespace: node-feature-discovery
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    master:
      revisionHistoryLimit: 3
      resources:
        limits:
          memory: 68Mi
        requests:
          cpu: 2m
          memory: 68Mi
    worker:
      config:
        core:
          noOwnerRefs: true
      resources:
        limits:
          memory: 70Mi
        requests:
          cpu: 3m
          memory: 70Mi
    gc:
      revisionHistoryLimit: 3
      resources:
        limits:
          memory: 23Mi
        requests:
          cpu: 1m
          memory: 23Mi
    prometheus:
      enable: true
