---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kube-prometheus-stack-alert
  namespace: monitoring
spec:
  summary: "Kube-Prometheus-Stack"
  providerRef:
    name: discord
  eventSeverity: info
  eventSources:
    - kind: HelmRepository
      name: 'prometheus-community'
      namespace: monitoring
    - kind: HelmChart
      name: 'monitoring-kube-prometheus-stack'
      namespace: monitoring
    - kind: HelmRelease
      name: 'kube-prometheus-stack'
      namespace: monitoring
