apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:DYHG2JbeJRuAmn0=,iv:hRT4phGM/ixTroC2uWZYS4F8bAZL8fh24NX5otYtcJY=,tag:kNxuuO1u6S906LAnGr/nJQ==,type:str]
  admin-password: ENC[AES256_GCM,data:R+iUNvfvKnKgNq+2JzhizH+Hj+U0vyQ0,iv:cXe3wPrDFaFx072jMQmx6qQxZSspvs8hSPr0TJwpR8M=,tag:XV/vxzW6xXFoz19DRs7zRQ==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNXgzeitBUW9maGR0U1Iv
        dUt0bEdaZjgzNDVxRjN3L3FsT3ZjNFJiMzI4CndBdmhCQVdaVzBOSE9rb1JoT1Y5
        SDlqc21RNmFQVFV3Z3p0VE9VWVVpb1EKLS0tIHlXdzBaeGNlZ3EvSGtVeHRWR3E3
        bFBlTzVPSVh3NlRzY1ZGb0Z0M1JZbHcKjm9Av9CYsgOFF0alkiV5Wi7TByx9l1/m
        jkE8LEnDqjvssbVXH8KjQeEI+vci5wK89mKlUIYpmiWPeoFzHB+XCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:46:44Z"
  mac: ENC[AES256_GCM,data:Qnf84hjk+CBppXq3HwMsx/KZI9tclOBMCtsV/C4uTPLeqHpk9buYMJPxqbjlcMSkLUMdEWBJaoev+6uZ5D1w2u72hJOBsIyKtwe3sUXaa90w7/7oKfXjpg6lPN2yjYXMSts4a6l+ssCwovTUELbI2vlVbVa7lU2/yd+tcHtofcs=,iv:G54BeUlN+YcoOkpfxvuW+jPqzMEc3LERMsYStWzKdyM=,tag:iCiGaBeaefCI/d1RjWfUZQ==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secret
  namespace: monitoring
stringData:
  DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:DBRpDfq1eorv5fqka2Sc4Pjz7AlLo0lBJISUVM52jXOK48ffCIWWDYZa9lF3kYFGGJWSFOVK3hNgKBgRlBFzBZj04Kfx8WCop37JmEHRH3ccpvW/gI26RWyiDPZnjVwOMpfHBXEL2aFQXt8eM/AqCuX61APLqxlutQ==,iv:dGQKcbZAVziA8GrnBNSGp8pjGyBuEtvA9t6n4uY4Ih8=,tag:qK1E5Kl0YxaCtH0PqZLimg==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNXgzeitBUW9maGR0U1Iv
        dUt0bEdaZjgzNDVxRjN3L3FsT3ZjNFJiMzI4CndBdmhCQVdaVzBOSE9rb1JoT1Y5
        SDlqc21RNmFQVFV3Z3p0VE9VWVVpb1EKLS0tIHlXdzBaeGNlZ3EvSGtVeHRWR3E3
        bFBlTzVPSVh3NlRzY1ZGb0Z0M1JZbHcKjm9Av9CYsgOFF0alkiV5Wi7TByx9l1/m
        jkE8LEnDqjvssbVXH8KjQeEI+vci5wK89mKlUIYpmiWPeoFzHB+XCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-20T15:46:44Z"
  mac: ENC[AES256_GCM,data:Qnf84hjk+CBppXq3HwMsx/KZI9tclOBMCtsV/C4uTPLeqHpk9buYMJPxqbjlcMSkLUMdEWBJaoev+6uZ5D1w2u72hJOBsIyKtwe3sUXaa90w7/7oKfXjpg6lPN2yjYXMSts4a6l+ssCwovTUELbI2vlVbVa7lU2/yd+tcHtofcs=,iv:G54BeUlN+YcoOkpfxvuW+jPqzMEc3LERMsYStWzKdyM=,tag:iCiGaBeaefCI/d1RjWfUZQ==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
