---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: endurain
  namespace: endurain
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs
  resources:
    requests:
      storage: 5Gi
