apiVersion: v1
kind: Secret
metadata:
  name: endurain-config
  namespace: endurain
stringData:
  SMTP_HOST: ENC[AES256_GCM,data:Y0r9jVGkGqqqhjxTmUc7HA==,iv:nHdegTo3gOgROZf2huX2JGody75RAito8JC792P3P0s=,tag:eEo5usgZloyrrYD/IumgmQ==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:WkHzSg==,iv:rDDFKsHWVPTaUvTLJlaTRakXh4V/SRb2v1nOYOg54pE=,tag:ZENOocUsgQSiDt6bROV/KA==,type:str]
  SMTP_USERNAME: ENC[AES256_GCM,data:jGtvc7TdRy+mR0MyzSomB+w=,iv:sgOxG3wUtrhppE6dPy3cd+3MV4QKFd6Qk/Kr8yhU2V0=,tag:pWRtAVBenIVmSDMVSApYMA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:QIkSkTuUkQpd/bvkufnaNg==,iv:cUel5qLnzLWJ5/Dv1fjABdOTceJVn4MCM5EElL1OzHk=,tag:HMVVu4A+1LK3Gq7Z7LWdJw==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:0jtpCUcFkBd6YanjOFp5NeFhlWKcCD/y9atht8wp/mY=,iv:V53wOEqHYj++nFdudqqycC/H4UaGRJ2OBVv9UkeEXZs=,tag:atNGGXVmQZGYb1UVorP7xw==,type:str]
data:
  FERNET_KEY: ENC[AES256_GCM,data:h7ICVfWe9712pD2HIfJaItwDb7esshBSWWeDFFblXZS5bjpXBMVDB96RSlgryGgw6MsvWRsRohC/U+c0,iv:1i7rpQJFcYYxRzvkn6FDfX4udJbEc+xMrbexXM2uIis=,tag:jYFPzQi+gUTbB7TVWYZOfA==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTzB3SmVHVTNIZEhwVFZ4
        Yi9ZRFlmbHFZT2FpMkVSNUNGc2kxMCs1S0h3ClZDWWc2cXY4dk5QL1VVdEw2bUVG
        c1pSSkxYdzFlNTRGTklRTGJzMU5leFUKLS0tIHRicjY5WWhCWVFvMUo4bWRpcU5K
        VmVRanBodEY4L1ZkMUVvVU55MW5PYk0Kkh4d5Y0J56K9zanRJ/H8DUCFE2FEBP0q
        qyqpCWJGR/5M4TqqxpnHGCMjLJNeMq+FjAoLRvwdKZr240jRd++GhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T23:40:35Z"
  mac: ENC[AES256_GCM,data:hXLNntlvEnmqkRIB/0oYDvAqH4n/ZWcU3AagKE5N6L8dGVTajbEggisz+IXuSNtiBXfOfYtW7h08FtygVfgfkGCUd8XY6L6GI1RD7BN3whCrMuRw1ELcGv/gWVGs01loSUnDtikfOhPdSeaXYuDa/JZw75oD4IOkBsI+K2+at9k=,iv:HswO8+vw1HhZyuuqzOBNrQE5qwMy410/x+iJlXYVSh4=,tag:qzGYryZoCs+mLkSKR/rcjg==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
