apiVersion: v1
stringData:
  username: ENC[AES256_GCM,data:G/1h,iv:2o8NrQRr1b18QqI/apfbmrOiG4gwhXP4gSyBIxzhhTQ=,tag:rHOEHuCya0yno/o+ouDuQQ==,type:str]
  password: ENC[AES256_GCM,data:OyFbuBVOUxixhRiVSvbw2LTJzV2o27K/y0GUMMcE,iv:HWGr+Uj3MuzBg35WXRB8eTvo5Hv4SctH3sKRHqApvog=,tag:GvBpiYmeHQ7zAbbybvOVkg==,type:str]
kind: Secret
metadata:
  name: media-creds
  namespace: kavita
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVWhsdXFVTFBqU1hTRnNQ
        TTBBbUFPNjJxSWtMWm5kM1RKZHMzQ1luZnlVCkgxSXFZckQ5ZTJuMHVBQmVubGF4
        ZjdMVXU1N2s2anhuaGVQOFhvTitkTVUKLS0tIGpkM3h0UlBqdDVlQnR5ODJvb3Fs
        bFgzSXdzLzZoa1lpL0VoR1hXWVNqcTQKdGlmQTDlcLjDoKAtI0O5wy7nWH6bSt9v
        9XNfjnKfIX9+gWu/cCIE86m2sAo69hE9xLvmt+/8trSFPMKnd6m75w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-15T00:02:02Z"
  mac: ENC[AES256_GCM,data:MWAgjf/WJbXXfBSNfFQWLmRj5H7yUO2vBHCIN/NlGB/2fNvTAasoFD8HqRmwjPVF1DFVfwssALJhmNRx7UGfUm1qQ/xnH3JV6viLiqHE647LSrLzbfIi2p0x2fBcpLVvCJgNXypQHxxrRiemGA0lqHSWgq0PgO9XpRcFP3qFiHA=,iv:gjSjZsoCOABE5SFwUPnRz/s6z+AYh5ijwi0lDTr20wc=,tag:Ix/Swj8hbO5hLQ+JD6p5Ow==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.11.0
