---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: localai
  namespace: localai
spec:
  backup:
    target: primary
    volumeSnapshot:
      className: rook-ceph-cephfs-snapclass
      snapshotOwnerReference: cluster
  bootstrap:
    initdb:
      database: localai
      owner: localai
  enableSuperuserAccess: true
  instances: 3
  storage:
    storageClass: rook-cephfs
    size: 2Gi
