---
apiVersion: v1
kind: Namespace
metadata:
  name: vllm
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: vllm
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
