apiVersion: v1
kind: Secret
metadata:
  name: james-creds
  namespace: shares
type: Opaque
stringData:
  PASSWORD: ENC[AES256_GCM,data:TWiZRlmigFqfqwtfnL6o/7MPSGD2K2LCQubRxPvq6RA=,iv:nTzQ9RU3hDoMi0P/lvefSdD1M151q0A7FjExIbaXrPc=,tag:jVbi3BucL9XbvXxZ+1RrwA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMVg4cXg2MlBYa1UydG9q
        NU9mM0ppYmtNRW41akgwSkRuU1BtNkV4ajNnCnV4SjNaRFRmNmk2NTdzUWNHZU9E
        UnFiMFNrQU8rSW40ODI4WmpKY2EvT1UKLS0tIDZjRnZWWWRLSjlqMkVMKzVJL0pv
        dXIxa0drdVlscnNCaTBHeUZReXY3VlEKBw+f+fkMlNQGJmCwUyCYw7zqZJzZxt09
        8XCsHX5Y0QVeAVhq7yoFSekqtV6ftB+cl6hgM1kGbkRX5MAubVzndQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-08-10T16:43:22Z"
  mac: ENC[AES256_GCM,data:YaoNr236FT+GXn30t+dE/eCTSHsjxIW3YPeh4sZq8HWfgPAf+oyUVEIv/HNeZZ+R5/5fFDY9PdH3bztAIkYUoTLjLaZ7GsB/wR+y3GjNfSWNzAAqddbd04PD6FrwhO23g+0us79LsCjbvIiFfWVl/mkRmyDN3sFu5AplDlezA9Y=,iv:xSbECodoribdY3bewRjVmQC2jxpGZcLBESwYIffM4s4=,tag:IC6SZutFlpk+jTde8gWYPA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: shanna-creds
  namespace: shares
type: Opaque
stringData:
  PASSWORD: ENC[AES256_GCM,data:wyaYSOTR7PUD7BcJjP2v/MRplUBwV3PaSv5iaqGDHC0=,iv:29vWMdxbyPGN5m8iKvKLWVeNbRKv3b1MO3lzrxo3ACA=,tag:ZG6GlKOqmZpns3lG3Sklxg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMVg4cXg2MlBYa1UydG9q
        NU9mM0ppYmtNRW41akgwSkRuU1BtNkV4ajNnCnV4SjNaRFRmNmk2NTdzUWNHZU9E
        UnFiMFNrQU8rSW40ODI4WmpKY2EvT1UKLS0tIDZjRnZWWWRLSjlqMkVMKzVJL0pv
        dXIxa0drdVlscnNCaTBHeUZReXY3VlEKBw+f+fkMlNQGJmCwUyCYw7zqZJzZxt09
        8XCsHX5Y0QVeAVhq7yoFSekqtV6ftB+cl6hgM1kGbkRX5MAubVzndQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-08-10T16:43:22Z"
  mac: ENC[AES256_GCM,data:YaoNr236FT+GXn30t+dE/eCTSHsjxIW3YPeh4sZq8HWfgPAf+oyUVEIv/HNeZZ+R5/5fFDY9PdH3bztAIkYUoTLjLaZ7GsB/wR+y3GjNfSWNzAAqddbd04PD6FrwhO23g+0us79LsCjbvIiFfWVl/mkRmyDN3sFu5AplDlezA9Y=,iv:xSbECodoribdY3bewRjVmQC2jxpGZcLBESwYIffM4s4=,tag:IC6SZutFlpk+jTde8gWYPA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
