apiVersion: v1
kind: Secret
metadata:
  name: james-creds
  namespace: shares
type: Opaque
stringData:
  PASSWORD: ENC[AES256_GCM,data:IfxCythYpz1qVu9B5nSWWTbwPQvkrJwJD5AlQ3A7LkI=,iv:3J0lXAvu0E65TKcdzDO5ue2U7U3AY/Wo3ezn+0g+3ec=,tag:5FoRxTgtzg1ZxcFYjDmMsA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYmR0aVp1aVhQQ3N0U2Zl
        VWsyL1RLN0Z4UmNKdzRjMGlleUowUjRMclM0CkUrTEkybTRkMFROSTFIdSsrbHZZ
        V2MwcjlvUytPbkk1SnhlcUxFV1hVcWsKLS0tIFMrN3hVV2FYZ2lVN2ZIczhna2pK
        WDFIK3EvV3RCMGlGamZpQmdmZWFEcm8KSGi0d6CvFyvOCtPNhlmmD1aRNcn9/mSI
        NBabF4nwwsR5xTbqGOX8NK8TRNYyKbjAgfmM6ngvEisYXedksTcDbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-21T02:48:07Z"
  mac: ENC[AES256_GCM,data:lXT2Ebj0OUUmS7+XmN9AndyH2suVKmivHmkV7bQ4miDyreVeRKY74PgcCFwsaLA5lvjq8cg4E/5LwRdYCC4h8Ee3yaR9FwpAp+ZaCIHT5sjC/gbpPtXR80/Qda8vMAOk3z/VzGHYkkWoLslBDuhBKxHQ8Ru1nTTrvzLnV7nFVnM=,iv:afANcRQD+Kdz5ErgvIUIcSud1S3eLHjq5HXMiMVDJvw=,tag:tOcNYt2cVgOBQiVwTNPR7Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
  name: shanna-creds
  namespace: shares
type: Opaque
stringData:
  PASSWORD: ENC[AES256_GCM,data:RGz7SHEQpOG0Uhbj3jJ7fViYFf4Eag81eRgdBrP8sGk=,iv:AAZ1u72Ld+80aGDqjW0ONBEMZJLFp9xQ9J+6JeGxeAM=,tag:rE8WxVk8KTllpponNAgcbQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYmR0aVp1aVhQQ3N0U2Zl
        VWsyL1RLN0Z4UmNKdzRjMGlleUowUjRMclM0CkUrTEkybTRkMFROSTFIdSsrbHZZ
        V2MwcjlvUytPbkk1SnhlcUxFV1hVcWsKLS0tIFMrN3hVV2FYZ2lVN2ZIczhna2pK
        WDFIK3EvV3RCMGlGamZpQmdmZWFEcm8KSGi0d6CvFyvOCtPNhlmmD1aRNcn9/mSI
        NBabF4nwwsR5xTbqGOX8NK8TRNYyKbjAgfmM6ngvEisYXedksTcDbw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
  encrypted_regex: ^(data|stringData|binaryData)$
  lastmodified: "2026-07-21T02:48:07Z"
  mac: ENC[AES256_GCM,data:lXT2Ebj0OUUmS7+XmN9AndyH2suVKmivHmkV7bQ4miDyreVeRKY74PgcCFwsaLA5lvjq8cg4E/5LwRdYCC4h8Ee3yaR9FwpAp+ZaCIHT5sjC/gbpPtXR80/Qda8vMAOk3z/VzGHYkkWoLslBDuhBKxHQ8Ru1nTTrvzLnV7nFVnM=,iv:afANcRQD+Kdz5ErgvIUIcSud1S3eLHjq5HXMiMVDJvw=,tag:tOcNYt2cVgOBQiVwTNPR7Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
