---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mealie
    spec:
      securityContext:
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911
        runAsNonRoot: true
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.15.1@sha256:62897c85f7db1882e4c9a67e7b9eed8c227096700e02450ba61d0b99a03cc605
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: mealie-config
          env:
            - name: ALLOW_SIGNUP
              value: "false"
            - name: DB_ENGINE
              value: "postgres"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mealie-superuser
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-superuser
                  key: password
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: mealie-app
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: mealie-app
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mealie-app
                  key: dbname
          command:
            - /app/run.sh
          volumeMounts:
            - mountPath: /app/data
              name: mealie
          workingDir: /
          resources:
            requests:
              cpu: 305m
              memory: 700Mi
            limits:
              memory: 700Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          startupProbe:
            httpGet:
              path: /api/app/about
              port: 9000
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/app/about
              port: 9000
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/app/about
              port: 9000
            periodSeconds: 10
      restartPolicy: Always
      volumes:
        - name: mealie
          persistentVolumeClaim:
            claimName: mealie
