apiVersion: v1
kind: Secret
metadata:
  name: mealie-config
  namespace: mealie
stringData:
  gpg-key: ENC[AES256_GCM,data:BgEFVEeUMtnX9fgrjMoKSj7DjDm7UWKxollrkV2yN2wd65UWXW0/TQ==,iv:v+YV3JTdojKLPLJtQw2nwq3hRTLFZtYzlOsD1Cnztj0=,tag:azhBwiawLxeojB51b5IT6g==,type:str]
  BASE_URL: ENC[AES256_GCM,data:wmOkikIrfUhD+q46VPktio9ad31MAA4=,iv:d76hbNyTbUOpnC5AJjoCMiddFp1uk3k3Y/XgCis72F0=,tag:Jc512ShqJW+GLgvJ2CwHtA==,type:str]
  OPENAI_BASE_URL: ENC[AES256_GCM,data:XJESOvvRhMAR8VcSS5ul77cu5wKBVJED21GiV2WgAXMGoZzkXLO2GJg0a1V1QTodxb5z5A==,iv:fKHnrTkQNNM9zgXH+rZi9Ox4guYiIKZAIsvdDrHRpjE=,tag:8Q6HjdgVRJeMAGMJrSrBKA==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:iSQ2TGb5ZmLyUENvFM+9oXVlQYYCilo+ngn4MRfa5m5ngDqBg1p9ionQvpTzMfY5wg==,iv:q/CgqpqyFSajvyzvjwirm13tUszEcyK1kP/LdIzsQF4=,tag:WGINgOV0oJ1BOiv4/Rjpvw==,type:str]
  OPENAI_MODEL: ENC[AES256_GCM,data:r6lNbIp/RFAfKOQ2nz+R3Crf9arj,iv:szlDaRN8m97X+Eh7yX13DsKBZSc1rsVmEOmhvOfd9g4=,tag:SVk87lcmnFBEwJG5voLenA==,type:str]
  OPENAI_AUDIO_MODEL: ENC[AES256_GCM,data:NaONqPJ6o3go8FZZ1DLdL1mT5l7/,iv:v6zLWGaUdhVMQpZRfo8w59dtXpP5f9/dnILrHy0h8yY=,tag:2dEAALNw/Zpyxucl8XKmig==,type:str]
  OPENAI_ENABLE_IMAGE_SERVICES: ENC[AES256_GCM,data:AZeMrg==,iv:pD4DpmmZH2C50BRn175eOW8tGzAb/58IpJMCjgIQP2E=,tag:rT4gpsjA8o6yM26irGJZ2g==,type:str]
  OPENAI_ENABLE_TRANSCRIPTION_SERVICES: ENC[AES256_GCM,data:LrhU8A==,iv:RbWK5qn6k+p1teboUVzp/JeJ5M4nR8MvRfSZra6+QkU=,tag:m0z583LiPQiQzKFrAIb0TQ==,type:str]
  SMTP_FROM_EMAIL: ENC[AES256_GCM,data:zlra/U2qjvgy2TdbQihD,iv:GY4R8Bj7nAABbcymIHyuBnHzGowaBc0VeknEDbl4ku8=,tag:vQbDhgsh96jTh+hYZXNUlg==,type:str]
  SMTP_HOST: ENC[AES256_GCM,data:UJlLHE+wIc6vlyFjti0DQg==,iv:DdipEQuAaIMXtM4jSP1Sgw8h5Ddbq1zdAanZSiGHBkw=,tag:OK5HoFebi7kgZLvrRB1WZg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:GDH/G1RNX3417R6Xrrz2SQ==,iv:jKGq6jjrEVfRLWvVUxlAjIJPROl+/ZsnQG58SYju6Hc=,tag:bz7VXaUt5C/oiUFfk1B1+A==,type:str]
  SMTP_PORT: ENC[AES256_GCM,data:GIzPgQ==,iv:oOAu6AsMu21jteEr88QrA/gRYmTYmq8ku3P90qf0za0=,tag:o9T1SD35sCxVTqmBX6pXPA==,type:str]
  SMTP_USER: ENC[AES256_GCM,data:Q42WCqNqJp+JYuFRJybN,iv:YPjqwCEMLYc5HTGqZYAfu3ifBzYFabFZ1IO5vzxpc4A=,tag:SVPuER/MD2T+G4BV7h2n+w==,type:str]
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmbkFUWUdwaGRqWng2Ujhw
        UHN2WS9oQ0RwemxhZGlWTXI3dithY2p4azJzCkJrSmxYUTF0Y3BOdGhNcnREY2FG
        Snpyd2Uxd3IyK3U1bG5rMU5WTWxEeTAKLS0tIE1EVytFS2ZUSm9PZGtpRlYzM1JN
        M3FDbGxlQzhRUW8rMlpQdFYxRGw1STgKLREHcV2H7wFq7Oug6pnbph1YoRIs/odx
        pNGy33FrryDjVnEX/1LJCF7LXQbZUWPK5qqFEFzylFjogMgigkBggA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T21:39:23Z"
  mac: ENC[AES256_GCM,data:rrg70JPsZtixRfLZkRqfAZyROTrzcaBJ9Mbchr6uxniknnGirtGzsg3314Ui6cH3P5R3uvrOtPS2fUDJmTUqHBTuM8n5EoTbaDl0zkry5TiQxZsi1yuTMkbagPQ1B9MVbANpCOvFIVJo+q+woNwcShRTSIqqQVn/6Zx0Pn8fxZ8=,iv:cln8t7MTRHob8SvFWqWdf+/8uehaD69HLiqq95vCjb0=,tag:glpJ9i3V6i2qcGRUzsPzyA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
