---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: volsync
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: volsync-alert
  namespace: volsync
spec:
  summary: "Volsync"
  providerRef:
    name: discord
  eventSeverity: info
  exclusionList:
    - "Dependencies do not meet ready condition"
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: volsync
    - kind: HelmRelease
      name: '*'
      namespace: volsync
    - kind: HelmRepository
      name: '*'
      namespace: volsync
