---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: discord
  namespace: renovate-operator
spec:
  type: discord
  secretRef:
    name: discord-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: renovate-operator-alert
  namespace: renovate-operator
spec:
  summary: "Renovate Operator"
  providerRef:
    name: discord
  eventSeverity: info
  exclusionList:
    - "Dependencies do not meet ready condition"
  eventSources:
    - kind: Kustomization
      name: 'renovate-operator'
      namespace: renovate-operator
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: renovate-config-alert
  namespace: renovate-operator
spec:
  summary: "Renovate Config"
  providerRef:
    name: discord
  eventSeverity: info
  exclusionList:
    - "Dependencies do not meet ready condition"
  eventSources:
    - kind: Kustomization
      name: 'renovate-config'
      namespace: renovate-operator
