---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./config/secret.sops.yaml
  - ./config/pv-media-smb-mjolnir.yaml
  - ./config/pvc-media-smb-mjolnir.yaml
  - ./config/cj.yaml
