---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-models
  namespace: vllm
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-cryo
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
