apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: vllm
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:8Saj96xB6xfWfR9RpElVDnAEf280SjqaEKO80YIsr8cToDsDpA==,iv:yArn8WNlOT6xKjDC9FpMv8bLR56hFYl/MakRRxcdus8=,tag:ZuAf+8oq6UR39n5dUL5Ixg==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzU2ZBNWYvbU95YTJZYnRB
        M0EvQ2hEV3Frek5UYXBxU1lrTm03REhOaUJJCi9WWmJVR3N0UHMvSDkyR2Z1WFNw
        RnJHb1VLelh1ZTc0QjFFdmplbUw5MDQKLS0tIEVlYXM3YWpCVVUzUXFNSitOK2Uw
        Z2JkQWpZdUlGd3JsL0ZGQ3JKZy8xeUkKun2mJTKV6PHP61qCuAiGMPCtCcFbvSwy
        CdOELo8AHjIMGZIUWZNKYIivraowxefJcYu2xYE0M0Cv0eMY+fGEjg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T23:54:27Z"
  mac: ENC[AES256_GCM,data:fI1Dmt3Xvgjow/qaBEl3POSjnWBVuBVs0orxOiXH4Jljb9XCdhntEbli4NWO2ip6zsCUoH15m3DKe5Z1u7jj+TsxRFjsT1P3Ax7Qir0jek6V18AGXs0NgQGxZpxpPooeLI6yqR6XwKQ4GUraJRF9q7ZOMcs5cPv8zrTBg66jxSU=,iv:lbWGnChSLc8J54fRbxVT0uTZqTSAicbRggtg9+uaNVQ=,tag:EXxioWB1UEJx91zJwIyBDA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
