apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: vllm
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:24Y30sq/SEbSb7iGKpAYbmFFAzWKx0mGoh3DTnK53fH6qVLIrg==,iv:jwSsSFzKzsYU1pXi9ze5kmwNmjzflemLHpIzpHZ8uGA=,tag:zb3iAcHUZmVx3zb/Kq8hFg==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZExkNGhPdk1pdWRuaUUy
        aU1MQytNR0RyMEVCU0crOXRDR1JWMDkrT0EwCnpMUEdBaS9FYTA2eVZJdE11dkov
        SkdOS0RneTFRTnBtaGxtWi84WUpod1EKLS0tIFFCb25IYk50N1hwNnE2WjNmbklY
        YU42MlhyYVYvTE43QjRMRUtaakcxcGsKGHNJHyOac/lJCUYyZ7UOE/pg9uxozWuD
        iC8WRE8YR26UfddsSmG8KIHKvWFDW/vJrsVQDZNA5cHtaLvYQd0BuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T00:08:04Z"
  mac: ENC[AES256_GCM,data:+1SnGONVyaTcWDvtXucxigroeGlWYuTENRZD9AAbsX0mDGXJKz19Hr+apRPXgipmMcYnhGyBgOpgxUsPcOaSNMf3jji5tyMg9d32HpefYAepb3QBqqm8CmJkMllXwSEBzVApBuY6d3dQKkhdCkZGMpMeJsaVDM/U3gUSfeQjeFo=,iv:DA5oDLzloO3DtBjvXamzl2v2ZUS5TBXJn+jvR9iXMVE=,tag:rYXaVZpOUio09qbot8S7og==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-key
  namespace: vllm
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:hoCaOB56DPevI2LkUy0IlOsm5e1fyCUwJTXGNN+N9FkHwPR1huL//0JjwPjeQFEWgQ==,iv:Q6NiPe5fTLmMqjA4fbtfmQFszyHsSadxVeVkaEBoMlM=,tag:yV+z2dE/VZiQPX39tx0GGA==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZExkNGhPdk1pdWRuaUUy
        aU1MQytNR0RyMEVCU0crOXRDR1JWMDkrT0EwCnpMUEdBaS9FYTA2eVZJdE11dkov
        SkdOS0RneTFRTnBtaGxtWi84WUpod1EKLS0tIFFCb25IYk50N1hwNnE2WjNmbklY
        YU42MlhyYVYvTE43QjRMRUtaakcxcGsKGHNJHyOac/lJCUYyZ7UOE/pg9uxozWuD
        iC8WRE8YR26UfddsSmG8KIHKvWFDW/vJrsVQDZNA5cHtaLvYQd0BuA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T00:08:04Z"
  mac: ENC[AES256_GCM,data:+1SnGONVyaTcWDvtXucxigroeGlWYuTENRZD9AAbsX0mDGXJKz19Hr+apRPXgipmMcYnhGyBgOpgxUsPcOaSNMf3jji5tyMg9d32HpefYAepb3QBqqm8CmJkMllXwSEBzVApBuY6d3dQKkhdCkZGMpMeJsaVDM/U3gUSfeQjeFo=,iv:DA5oDLzloO3DtBjvXamzl2v2ZUS5TBXJn+jvR9iXMVE=,tag:rYXaVZpOUio09qbot8S7og==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
