apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: vllm
type: Opaque
stringData:
  token: ENC[AES256_GCM,data:AUU8/naqHL5/8MC8FN9Cy2cPVRjTjFYRilldkzRhKPwtcnyNmw==,iv:1HPyr4KKOn9jnPldniFUYoO6OdSOP7+4aov7SJBOe5s=,tag:AS5KUxXbuxnFKqu/IqnBuA==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRWRIb0QyblIrdlhjNmpt
        QjlzOWUzT3A1SGYraHFmRk9JSm5NclpPZVdjCnRDR1hROEFKMEhZS0NzN1lvOEpC
        Y1pQcjBnMmdodlEwTlNmQSsvYnpCcXMKLS0tIDNtTDJTUkU0M0dPdTZKL084Qmhl
        US9Mc1lWZlhQTGdtTGZHM2JZYlJzVnMK6xDPWHfsyl/iPf/TfZDiQPKczHV4nzhh
        5513Whgv09MJyZ2LSj/roIeZFnDNgbbdz42/XhJiD8y5KJXNixiKHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T00:24:04Z"
  mac: ENC[AES256_GCM,data:JN+EXnsUx6uymUjIXKkvgQnwNi2f35K6V6tXaBDRrrNX6lJIqgjqruyuhmM9zesoUQ4ckd3mpRDbIschi3YheH+cRy20qu2a3H/2pNkGYUxfr88Zv+Rgi6p4glalM2DXMG9TV2DjzCOdR1SRcrVPKZHUr+0aFt2noYJJ8FfBUio=,iv:qhAS76m6A6/117LuhJK7VgEVDl67ibSTV/2shFYxino=,tag:Q9gSaDxHNQ+9PzLun8SXPQ==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-api-key
  namespace: vllm
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: openwebui
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: openwebui
type: Opaque
stringData:
  api-key: ENC[AES256_GCM,data:V+5WCUhZteFTfOlKAyj7vdj3ZUy/I4uRKfWa3afHink96a6jwpIXsNrH2xbuXQQlPw==,iv:SGjoCWlsQUgIS1X1TE9XwIhhC9LhTVUR32OOUa324YY=,tag:Chz2mFzrehpJgUCIKnRjAg==,type:str]
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRWRIb0QyblIrdlhjNmpt
        QjlzOWUzT3A1SGYraHFmRk9JSm5NclpPZVdjCnRDR1hROEFKMEhZS0NzN1lvOEpC
        Y1pQcjBnMmdodlEwTlNmQSsvYnpCcXMKLS0tIDNtTDJTUkU0M0dPdTZKL084Qmhl
        US9Mc1lWZlhQTGdtTGZHM2JZYlJzVnMK6xDPWHfsyl/iPf/TfZDiQPKczHV4nzhh
        5513Whgv09MJyZ2LSj/roIeZFnDNgbbdz42/XhJiD8y5KJXNixiKHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-23T00:24:04Z"
  mac: ENC[AES256_GCM,data:JN+EXnsUx6uymUjIXKkvgQnwNi2f35K6V6tXaBDRrrNX6lJIqgjqruyuhmM9zesoUQ4ckd3mpRDbIschi3YheH+cRy20qu2a3H/2pNkGYUxfr88Zv+Rgi6p4glalM2DXMG9TV2DjzCOdR1SRcrVPKZHUr+0aFt2noYJJ8FfBUio=,iv:qhAS76m6A6/117LuhJK7VgEVDl67ibSTV/2shFYxino=,tag:Q9gSaDxHNQ+9PzLun8SXPQ==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
