---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localai
  namespace: localai
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: localai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: localai
  template:
    metadata:
      labels:
        app.kubernetes.io/name: localai
    spec:
      containers:
        - name: localai
          image: quay.io/go-skynet/local-ai:v4.1.3-gpu-nvidia-cuda-13@sha256:60698083e10e2739523a7b55e6bbfa8a83ac86bb5715ca9eaca243f6cdd21f1a
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: localai-app
                  key: fqdn-uri
                  optional: false
          envFrom:
            - secretRef: 
                name: localai-environment
                optional: false
          volumeMounts:
            - name: models
              mountPath: /models
            - name: backends
              mountPath: /backends
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
            - name: root
              mountPath: /root
          resources:
            requests:
              cpu: "4"
              memory: 4Gi
              nvidia.com/gpu: "1"
            limits:
              cpu: "6"
              memory: 8Gi
              nvidia.com/gpu: "1"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
            timeoutSeconds: 5
      runtimeClassName: nvidia
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: localai-models
        - name: backends
          persistentVolumeClaim:
            claimName: localai-backends
        - name: data
          persistentVolumeClaim:
            claimName: localai-data
        - name: tmp
          emptyDir:
            sizeLimit: 20Gi
        - name: root
          emptyDir:
            sizeLimit: 1Gi
