apiVersion: v1
stringData:
  API_KEY: ENC[AES256_GCM,data:QzBa6O/5mvpo+0Ai2atvPvtbC8agq70OZ338JPHq4F5gFB5VdVX+kSilz3imNVIaritZ12FmtH19R+AGhRQaO4NVwbCkygA=,iv:ek+Vgc3ZDFUVB3Ahp69Gl7f0lCCDHNxWPsGx3H9M+F8=,tag:7OGYvGfg5cTkEe7rGCbjuw==,type:str]
  DISABLE_WEBUI: ENC[AES256_GCM,data:cOnh7Iw=,iv:Tfy+8mVHdofjGTQGWFl9LjAlOiyPpiu9hVgIc1FXj50=,tag:bgzNgzkCgCysGwZIo5gs8g==,type:str]
  LOCALAI_AUTH: ENC[AES256_GCM,data:CMufOQ==,iv:Am4ZwkfiFbuV/ZRw3jtZ1//kXfiNMVkT5azlQyu2vbw=,tag:SesvOZPsvLSF5mCIh0CHxQ==,type:str]
  THREADS: ENC[AES256_GCM,data:nQ==,iv:X9ynE41qCpoat2rxLe6HA0zLp75F7t4ZRFNtD3Jt0A8=,tag:MTAGwJCmQvDykmgI3rgd4w==,type:str]
  MODELS_PATH: ENC[AES256_GCM,data:QlDjLyqr6Q==,iv:SWcBcEnYZZsNwmOFwpYzdzrI4Shs1oh0NXDZjjU5Jvw=,tag:0AxCYbmHBCv2ebTtrhJFew==,type:str]
  PARALLEL_REQUESTS: ENC[AES256_GCM,data:Hg3n7A==,iv:iDzxu3/SSzpMnR5h1xd1n2u0XL0G+u9v2dCbiICh5y8=,tag:AXmW+KBVptGC5r4YXKuOJA==,type:str]
  CONTEXT_SIZE: ENC[AES256_GCM,data:Bt50ujA=,iv:hGnxZdd80OsZwiRi0VyS/uVYuYd8pZUQGGODMTFTEg4=,tag:LnaPx2QjUVQ++n16UX6fgA==,type:str]
  LOCALAI_ADMIN_EMAIL: ENC[AES256_GCM,data:CbwuH4BXVKFfc02hvfqx,iv:zfQzLB1NJdzHiPgMmS3yegXwz1AcAnM2Rdo+8lSD8+k=,tag:stob4KyDIpq09YClsX2CMw==,type:str]
  LOCALAI_REGISTRATION_MODE: ENC[AES256_GCM,data:lfUfXR7w+cM=,iv:Q5uIPCAsEYX73Y567keWN/TWg4oX6NWxD7hG2b1pDoo=,tag:2cp4kvZ6Dy5cLESCx0FujQ==,type:str]
kind: Secret
metadata:
  name: localai-environment
  namespace: localai
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdENEVitBOThuMmhQRVRn
        WC9jdFQ3cTRQcGhnM3RiWDlWZzNXOGJta3dZCjdSVjdycFJyTll0ZzFIcHR3OCsx
        V2p4MTExMjA0eDE0VEdNcHVOd3pYRGcKLS0tIEJ3T3Q2SURMTkZOM2RBYjY2WGpn
        Um9ZcHRaMHdGUjl5NlRrWWh3RlEvTGcKoxqJofyl1DydpnvkiA2TjXnDbAsfbxKY
        tDBlxXXeoMjbFpGUPTBrULkeMj8JvJhML/87jH72nfAknqKpYFpE4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T04:55:45Z"
  mac: ENC[AES256_GCM,data:EuW46w0AWk0YST/FZkhpMKu5/c06e5b/EVFUq51T03nlbFh2ZseuIpcMnYpVbzz1/bW+yhZoJ5S5ZygsPSqxFfVEEQdiuWL5ERGsrcFdUS/NiV3d1dbi7jpMpVWJcWqSOUnBsIkryq+gSAcn2eU1Yiip767UJbjR9zhGCKVuffo=,iv:eERFv6Yuxcd+lnGJCP3DzQ7o1TFUSFQn7vkwpC4jc2c=,tag:RLNKBFEYRfy1SKgtu8h0cA==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
