apiVersion: v1
stringData:
  API_KEY: ENC[AES256_GCM,data:jsOUmMWBQoc5d6mXdCSl6+Y6rQ1CbytwyBu58y1hX/rUhry4yUFxUnyAfOPr4h+z3OVmkv2VLNbBhWPrix4a2mnwQpM9wa8=,iv:fZjjk979boVE//KpFNwj/1F3yUQDOjr35Q8Q2tnUyLA=,tag:PsQDKnIe4qx2oVIr1GlLCQ==,type:str]
  DISABLE_WEBUI: ENC[AES256_GCM,data:omadkYE=,iv:Pc6gQjM5i0rEETLYHXfsxW/dUa6LbwdvU9vl1EFup90=,tag:iUPqkKkAfTF/eO5DuqU1XA==,type:str]
  LOCALAI_AUTH: ENC[AES256_GCM,data:ugqwFQ==,iv:rYFqJf56A+H+SzlXb+9h1KJ04Pp5gdsWSaOd0tVm2Fk=,tag:V679RIxijBfjxLxjDLHNKg==,type:str]
  THREADS: ENC[AES256_GCM,data:fA==,iv:CWHfvysdymPcieWtjj/aJ3LevjpDnvUOPhHQ7+B/wwI=,tag:o9WM4wxoIYs2vVuSTw7bpw==,type:str]
  MODELS_PATH: ENC[AES256_GCM,data:1XplIHelBA==,iv:zabZxEXkQUhOJ112Oe8pMvE2zkPyGPIvFz9MigBvyic=,tag:jGtkvwaOZSJxMwKu3YK5Ig==,type:str]
  PARALLEL_REQUESTS: ENC[AES256_GCM,data:48KT4g==,iv:29Xd5oG19KF28+Z+puqbPCSwytaN2SVhsa5GyBUxB8Q=,tag:sOphUHKGP51ww90nL4Dntw==,type:str]
  CONTEXT_SIZE: ENC[AES256_GCM,data:RWvZnug=,iv:HwiHwXBEYPqQ7m5bW0t0GyWL91mO0Y16oaCcLpV/jRE=,tag:tx5nf3YzU1TXDBuTfyveGg==,type:str]
  LOCALAI_ADMIN_EMAIL: ENC[AES256_GCM,data:Nu/seYUz+nAU5UbDswzO,iv:OQocLJP4VMIfLE9f4hTwuouNR6G25p2kO+ZO7afNPzM=,tag:3nIzxi5lQi/Zeez3XxCDBw==,type:str]
kind: Secret
metadata:
  name: localai-environment
  namespace: localai
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOTYrU3pSSnJKbUtTWXBa
        U2hRRGxOUE54MUpWaHRBM3N6Y3FHNlBZQ1JrCmQyWWZsaUVkWHJuL2M5Q21ja1RO
        eXhhMitaTnRVZkNRdHI3YnVSMnU4UzQKLS0tICtzR2hqU3N2c0xwcm45MDZ2SDJB
        TkNTNklOVnVnNFZrWTlUa29ETUNRb3cKsUq3piXnUfnf+itoh3apxYQXHcoz0hOr
        4HTma+/rMn0i4CB1VutCxUpVXyDabgYYcXss/R0vCTR5uITRriUjxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T00:28:48Z"
  mac: ENC[AES256_GCM,data:7w7g3GZCXJkeB/JY80AUDcN2yNvOgfpODp3f9L7V2x+Gr/hkXVKtWvsNoSxSpSjZXqSW14ZfsXz6gEBDi5SgJvNjI6Ngfk6D5iktTZ7k7/SaKdMjqRICmCAFQBau5Tn5Texi54vcVQNoc6Ia0a8++zaCkNyc8wMD/ge3Pigpw4s=,iv:mK2IEXJnHvG9z+IKC5uhbiEYvI8TdFYYBWgyqXSN1yA=,tag:iwSASvEr2f04wxiXL2dgBg==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
