apiVersion: v1
stringData:
  API_KEY: ENC[AES256_GCM,data:dYAYiBkvxCIA+eaFkrgUs2Ycv0wmW0SCrwzTwFpUT8xyj15CXiSUUWFaV8oAFRTLIEdizj5n1w4StY9/TtavWaeFIvXd8YA=,iv:dAuGUXLOZbkG5Tu4I3eOi92CKwx6b/0oNch/plKO9h8=,tag:vAnUcYQON6Hv6/I9rWjpaQ==,type:str]
  DISABLE_WEBUI: ENC[AES256_GCM,data:fLGTRpw=,iv:SazyDpsxP9o3jRTdIMgngpFMsa6kMHJnbHzpovAdWsM=,tag:ZcmSbi9aKW4foI3aCVhspA==,type:str]
  LOCALAI_AUTH: ENC[AES256_GCM,data:12VhLw==,iv:CXH9kbo59lU0ckLbjRTWxK5sexwixWpucTD4UMtAFJc=,tag:S+8CMbzgmO4ogF8h5MhmoQ==,type:str]
  THREADS: ENC[AES256_GCM,data:jA==,iv:JzfrjG8CZv4KR58JM40AWLx2dSna3Pdkb7gDkBMz2vw=,tag:8Axou/0wVbFlVOCq7yo63Q==,type:str]
  MODELS_PATH: ENC[AES256_GCM,data:SkVbGz3z3A==,iv:zskhJkQJ3mxYo97qDCLHTOeq/YB6NvhcaO2vnWXTEMA=,tag:KwHM6+txvmJTzlELHRHEOA==,type:str]
  PARALLEL_REQUESTS: ENC[AES256_GCM,data:d0MMHQ==,iv:gh7zz7EN8peb+8VHhOZ0vWc6U10bY7IA/GrDgXPp9Vw=,tag:OFEOLRTUzrozpKDj1fu0xQ==,type:str]
  CONTEXT_SIZE: ENC[AES256_GCM,data:M4LOQgc=,iv:tLaL0ULS2A4/Gp77YNiv6nKiHlHaEpwkMPnijeFMfuw=,tag:R8g/aTjhIeyVbW0lbNJCSQ==,type:str]
  LOCALAI_ADMIN_EMAIL: ENC[AES256_GCM,data:pF98pQ9IloPmP80V72t4,iv:MCzNFc2bA27C1lWFsnr4/PNCZloRi3cTLIp3DVjzYd0=,tag:+3q55Lj6V6uSm2LZb39duw==,type:str]
  LOCALAI_REGISTRATION_MODE: ENC[AES256_GCM,data:F3AD2970YYs=,iv:mN1WA0NpG9H9f3ha9YkGc22DqFQ3mPxqBI86WTmgrVg=,tag:c9whiia8LoxQmQ0Oe1zDrQ==,type:str]
kind: Secret
metadata:
  name: localai-environment
  namespace: localai
type: Opaque
sops:
  age:
    - recipient: age15zy2kyfe33wlart8c6e67vlnjls8ktwaf9fkg2plg5nh7xq6kdvq6e6t9v
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYWgxb1VqRktIOXFtS2s2
        RzV4akQwRDNRdlJmeTc5WVRsejBLVTl0dVFZClBreE9uRy9mTXIzQmgxUGIzNURS
        YnFGeHVZN0V6dTJLMWI2aWsyTys1OTgKLS0tIC9NRzFaTVI2aGtuU2FWKzU3NWIz
        MGRaNGVsb29JcXRLOHJ6dWcvQjliYW8K7TWKVTDLJvLZHjKHEm3eXc1aFVVOev5H
        jGoTl106CJ91oNILnDX+PUQUWoHXtv7DrAxMBOoiSkqB5fzyGyGuYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T00:36:25Z"
  mac: ENC[AES256_GCM,data:WjwjFFPZCmHa9gzBazyNKud71FX88nNhQ9JBIqPM5XtULl2YVhYxhtvAUDQxSrJknL5JCGVPHenl8zMh75Pi60+mjDKpS3BGIUZEbMDfBjHBWgu2trLf8mxA7sQSAYh1kRbrZKgU2Zm1xZ5Mmg0fgc5anpAD2hQJ6Qe87cEQ5Yg=,iv:tR7+kKH/ro2+T7+R17IbK3tnDCyhraOesNMvTWJ6gvE=,tag:Efalf6WiETxquZqDTE6T5Q==,type:str]
  encrypted_regex: ^(data|stringData|binaryData)$
  mac_only_encrypted: true
  version: 3.12.2
