---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: peej11-homelab-runner-set
  namespace: arc-runners
spec:
  chartRef:
    kind: OCIRepository
    name: arc-runner-set
  interval: 24h
  values:
    containerMode:
      type: "kubernetes"
    githubConfigUrl: "https://github.com/Peej11/homelab"
    githubConfigSecret: arc-token
    maxRunners: 10
    minRunners: 1
    runnerScaleSetName: peej11-homelab
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:2.333.0@sha256:1ad983536759ceec39ed75a2c8f007ca8c37b66eee35ed86f13623b29a4db97d
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RUNNER_CONTAINER_HOOKS
                value: /home/runner/k8s/index.js
              - name: ACTIONS_RUNNER_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "true"
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
        volumes:
          - name: work
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes: ["ReadWriteOnce"]
                  storageClassName: "rook-cephfs"
                  resources:
                    requests:
                      storage: 1Gi
